/**
 * Generate a comprehensive emoji calendar for 3 years (1096 days)
 * Includes variety across categories, avoids duplicates, political content, and flags
 */

import { writeFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Comprehensive emoji collection organized by category
const emojiCategories = {
	objects: [
		{ emoji: "🛝", name: "Playground Slide" },
		{ emoji: "🎉", name: "Party Popper" },
		{ emoji: "🎨", name: "Artist Palette" },
		{ emoji: "💎", name: "Gem Stone" },
		{ emoji: "🎯", name: "Direct Hit" },
		{ emoji: "🎮", name: "Video Game" },
		{ emoji: "📚", name: "Books" },
		{ emoji: "🎪", name: "Circus Tent" },
		{ emoji: "🎵", name: "Musical Note" },
		{ emoji: "🏆", name: "Trophy" },
		{ emoji: "🎁", name: "Wrapped Gift" },
		{ emoji: "🔮", name: "Crystal Ball" },
		{ emoji: "🎬", name: "Clapper Board" },
		{ emoji: "🎤", name: "Microphone" },
		{ emoji: "🎺", name: "Trumpet" },
		{ emoji: "🎻", name: "Violin" },
		{ emoji: "🥁", name: "Drum" },
		{ emoji: "🎹", name: "Musical Keyboard" },
		{ emoji: "🎧", name: "Headphone" },
		{ emoji: "📻", name: "Radio" },
		{ emoji: "📱", name: "Mobile Phone" },
		{ emoji: "💻", name: "Laptop" },
		{ emoji: "⌚", name: "Watch" },
		{ emoji: "⏰", name: "Alarm Clock" },
		{ emoji: "📷", name: "Camera" },
		{ emoji: "📺", name: "Television" },
		{ emoji: "🎥", name: "Movie Camera" },
		{ emoji: "🔦", name: "Flashlight" },
		{ emoji: "💡", name: "Light Bulb" },
		{ emoji: "🔋", name: "Battery" },
		{ emoji: "🔌", name: "Electric Plug" },
		{ emoji: "🖥️", name: "Desktop Computer" },
		{ emoji: "⌨️", name: "Keyboard" },
		{ emoji: "🖱️", name: "Computer Mouse" },
		{ emoji: "🖨️", name: "Printer" },
		{ emoji: "💾", name: "Floppy Disk" },
		{ emoji: "💿", name: "Optical Disk" },
		{ emoji: "📀", name: "DVD" },
		{ emoji: "🎞️", name: "Film Frames" },
		{ emoji: "📹", name: "Video Camera" },
		{ emoji: "📞", name: "Telephone Receiver" },
		{ emoji: "☎️", name: "Telephone" },
		{ emoji: "📠", name: "Fax Machine" },
		{ emoji: "📡", name: "Satellite Antenna" },
		{ emoji: "🔭", name: "Telescope" },
		{ emoji: "🔬", name: "Microscope" },
		{ emoji: "🩺", name: "Stethoscope" },
		{ emoji: "💉", name: "Syringe" },
		{ emoji: "💊", name: "Pill" },
		{ emoji: "🧬", name: "DNA" },
		{ emoji: "🔩", name: "Nut and Bolt" },
		{ emoji: "⚙️", name: "Gear" },
		{ emoji: "🔧", name: "Wrench" },
		{ emoji: "🔨", name: "Hammer" },
		{ emoji: "⚒️", name: "Hammer and Pick" },
		{ emoji: "🛠️", name: "Hammer and Wrench" },
		{ emoji: "⛏️", name: "Pick" },
		{ emoji: "🔪", name: "Kitchen Knife" },
		{ emoji: "🗡️", name: "Dagger" },
		{ emoji: "⚔️", name: "Crossed Swords" },
		{ emoji: "🛡️", name: "Shield" },
		{ emoji: "🧨", name: "Firecracker" },
		{ emoji: "🎆", name: "Fireworks" },
		{ emoji: "🎇", name: "Sparkler" },
		{ emoji: "🎀", name: "Ribbon" },
		{ emoji: "🎗️", name: "Reminder Ribbon" },
		{ emoji: "🎟️", name: "Admission Tickets" },
		{ emoji: "🎫", name: "Ticket" },
		{ emoji: "🏅", name: "Sports Medal" },
		{ emoji: "🥇", name: "1st Place Medal" },
		{ emoji: "🥈", name: "2nd Place Medal" },
		{ emoji: "🥉", name: "3rd Place Medal" },
		{ emoji: "🎖️", name: "Military Medal" },
		{ emoji: "🧩", name: "Puzzle Piece" },
		{ emoji: "🎲", name: "Game Die" },
		{ emoji: "🎰", name: "Slot Machine" },
		{ emoji: "🕹️", name: "Joystick" },
		{ emoji: "🃏", name: "Joker" },
		{ emoji: "🀄", name: "Mahjong Red Dragon" },
		{ emoji: "🎴", name: "Flower Playing Cards" },
		{ emoji: "🧸", name: "Teddy Bear" },
		{ emoji: "🪅", name: "Piñata" },
		{ emoji: "🪆", name: "Nesting Dolls" },
		{ emoji: "🖼️", name: "Framed Picture" },
		{ emoji: "🧵", name: "Thread" },
		{ emoji: "🪡", name: "Sewing Needle" },
		{ emoji: "🧶", name: "Yarn" },
		{ emoji: "🪢", name: "Knot" },
		{ emoji: "🎱", name: "Pool 8 Ball" },
		{ emoji: "🪀", name: "Yo-Yo" },
		{ emoji: "🪁", name: "Kite" },
		{ emoji: "🔑", name: "Key" },
		{ emoji: "🗝️", name: "Old Key" },
		{ emoji: "🔓", name: "Unlocked" },
		{ emoji: "🔒", name: "Locked" },
		{ emoji: "🔐", name: "Locked with Key" },
		{ emoji: "🔏", name: "Locked with Pen" },
		{ emoji: "🔔", name: "Bell" },
		{ emoji: "🔕", name: "Bell with Slash" },
		{ emoji: "🔖", name: "Bookmark" },
		{ emoji: "🏷️", name: "Label" },
		{ emoji: "💰", name: "Money Bag" },
		{ emoji: "💴", name: "Yen Banknote" },
		{ emoji: "💵", name: "Dollar Banknote" },
		{ emoji: "💶", name: "Euro Banknote" },
		{ emoji: "💷", name: "Pound Banknote" },
		{ emoji: "💸", name: "Money with Wings" },
		{ emoji: "💳", name: "Credit Card" },
		{ emoji: "🧾", name: "Receipt" },
		{ emoji: "💹", name: "Chart Increasing with Yen" },
		{ emoji: "✉️", name: "Envelope" },
		{ emoji: "📧", name: "E-Mail" },
		{ emoji: "📨", name: "Incoming Envelope" },
		{ emoji: "📩", name: "Envelope with Arrow" },
		{ emoji: "📤", name: "Outbox Tray" },
		{ emoji: "📥", name: "Inbox Tray" },
		{ emoji: "📦", name: "Package" },
		{ emoji: "📫", name: "Closed Mailbox with Raised Flag" },
		{ emoji: "📪", name: "Closed Mailbox with Lowered Flag" },
		{ emoji: "📬", name: "Open Mailbox with Raised Flag" },
		{ emoji: "📭", name: "Open Mailbox with Lowered Flag" },
		{ emoji: "📮", name: "Postbox" },
		{ emoji: "🗳️", name: "Ballot Box with Ballot" },
		{ emoji: "✏️", name: "Pencil" },
		{ emoji: "✒️", name: "Black Nib" },
		{ emoji: "🖋️", name: "Fountain Pen" },
		{ emoji: "🖊️", name: "Pen" },
		{ emoji: "🖌️", name: "Paintbrush" },
		{ emoji: "🖍️", name: "Crayon" },
		{ emoji: "📝", name: "Memo" },
		{ emoji: "💼", name: "Briefcase" },
		{ emoji: "📁", name: "File Folder" },
		{ emoji: "📂", name: "Open File Folder" },
		{ emoji: "🗂️", name: "Card Index Dividers" },
		{ emoji: "📅", name: "Calendar" },
		{ emoji: "📆", name: "Tear-Off Calendar" },
		{ emoji: "🗒️", name: "Spiral Notepad" },
		{ emoji: "🗓️", name: "Spiral Calendar" },
		{ emoji: "📇", name: "Card Index" },
		{ emoji: "📈", name: "Chart Increasing" },
		{ emoji: "📉", name: "Chart Decreasing" },
		{ emoji: "📊", name: "Bar Chart" },
		{ emoji: "📋", name: "Clipboard" },
		{ emoji: "📌", name: "Pushpin" },
		{ emoji: "📍", name: "Round Pushpin" },
		{ emoji: "📎", name: "Paperclip" },
		{ emoji: "🖇️", name: "Linked Paperclips" },
		{ emoji: "📏", name: "Straight Ruler" },
		{ emoji: "📐", name: "Triangular Ruler" },
		{ emoji: "✂️", name: "Scissors" },
		{ emoji: "🗃️", name: "Card File Box" },
		{ emoji: "🗄️", name: "File Cabinet" },
		{ emoji: "🗑️", name: "Wastebasket" },
		{ emoji: "🔒", name: "Locked" },
		{ emoji: "🔓", name: "Unlocked" },
		{ emoji: "🔐", name: "Locked with Key" },
		{ emoji: "🔏", name: "Locked with Pen" },
		{ emoji: "🔎", name: "Magnifying Glass Tilted Right" },
		{ emoji: "🔍", name: "Magnifying Glass Tilted Left" },
		{ emoji: "🔫", name: "Water Gun" },
		{ emoji: "🏹", name: "Bow and Arrow" },
		{ emoji: "🎣", name: "Fishing Pole" },
		{ emoji: "🥢", name: "Chopsticks" },
		{ emoji: "🍴", name: "Fork and Knife" },
		{ emoji: "🥄", name: "Spoon" },
		{ emoji: "🔪", name: "Kitchen Knife" },
		{ emoji: "🏺", name: "Amphora" },
		{ emoji: "🌐", name: "Globe with Meridians" },
		{ emoji: "🗺️", name: "World Map" },
		{ emoji: "🧭", name: "Compass" },
		{ emoji: "🧳", name: "Luggage" },
		{ emoji: "⌛", name: "Hourglass Done" },
		{ emoji: "⏳", name: "Hourglass Not Done" },
		{ emoji: "⌚", name: "Watch" },
		{ emoji: "⏰", name: "Alarm Clock" },
		{ emoji: "⏱️", name: "Stopwatch" },
		{ emoji: "⏲️", name: "Timer Clock" },
		{ emoji: "🕰️", name: "Mantelpiece Clock" },
	],

	nature: [
		{ emoji: "🌟", name: "Star" },
		{ emoji: "🌈", name: "Rainbow" },
		{ emoji: "🌺", name: "Hibiscus" },
		{ emoji: "🌙", name: "Crescent Moon" },
		{ emoji: "☀️", name: "Sun" },
		{ emoji: "🌊", name: "Water Wave" },
		{ emoji: "⚡", name: "High Voltage" },
		{ emoji: "🌸", name: "Cherry Blossom" },
		{ emoji: "🌻", name: "Sunflower" },
		{ emoji: "🌵", name: "Cactus" },
		{ emoji: "🌴", name: "Palm Tree" },
		{ emoji: "🌹", name: "Rose" },
		{ emoji: "🌿", name: "Herb" },
		{ emoji: "🍀", name: "Four Leaf Clover" },
		{ emoji: "🌾", name: "Sheaf of Rice" },
		{ emoji: "🌷", name: "Tulip" },
		{ emoji: "🌼", name: "Blossom" },
		{ emoji: "🌲", name: "Evergreen Tree" },
		{ emoji: "🍁", name: "Maple Leaf" },
		{ emoji: "🌳", name: "Deciduous Tree" },
		{ emoji: "🍂", name: "Fallen Leaf" },
		{ emoji: "🌱", name: "Seedling" },
		{ emoji: "☘️", name: "Shamrock" },
		{ emoji: "🎋", name: "Tanabata Tree" },
		{ emoji: "🪴", name: "Potted Plant" },
		{ emoji: "🏵️", name: "Rosette" },
		{ emoji: "🎍", name: "Pine Decoration" },
		{ emoji: "🪵", name: "Wood" },
		{ emoji: "💐", name: "Bouquet" },
		{ emoji: "🥀", name: "Wilted Flower" },
		{ emoji: "🍄", name: "Mushroom" },
		{ emoji: "💧", name: "Droplet" },
		{ emoji: "💦", name: "Sweat Droplets" },
		{ emoji: "☁️", name: "Cloud" },
		{ emoji: "⛅", name: "Sun Behind Cloud" },
		{ emoji: "⛈️", name: "Cloud with Lightning" },
		{ emoji: "🌤️", name: "Sun Behind Small Cloud" },
		{ emoji: "🌥️", name: "Sun Behind Large Cloud" },
		{ emoji: "🌦️", name: "Sun Behind Rain Cloud" },
		{ emoji: "🌧️", name: "Cloud with Rain" },
		{ emoji: "🌨️", name: "Cloud with Snow" },
		{ emoji: "🌩️", name: "Cloud with Lightning" },
		{ emoji: "🌬️", name: "Wind Face" },
		{ emoji: "❄️", name: "Snowflake" },
		{ emoji: "☃️", name: "Snowman" },
		{ emoji: "⛄", name: "Snowman Without Snow" },
		{ emoji: "💨", name: "Dashing Away" },
		{ emoji: "🌫️", name: "Fog" },
		{ emoji: "🪨", name: "Rock" },
		{ emoji: "🔥", name: "Fire" },
		{ emoji: "🏔️", name: "Snow-Capped Mountain" },
		{ emoji: "⛰️", name: "Mountain" },
		{ emoji: "🌋", name: "Volcano" },
		{ emoji: "🗻", name: "Mount Fuji" },
		{ emoji: "🏕️", name: "Camping" },
		{ emoji: "🏖️", name: "Beach with Umbrella" },
		{ emoji: "🏜️", name: "Desert" },
		{ emoji: "🏝️", name: "Desert Island" },
		{ emoji: "🏞️", name: "National Park" },
		{ emoji: "🌅", name: "Sunrise" },
		{ emoji: "🌄", name: "Sunrise Over Mountains" },
		{ emoji: "🌠", name: "Shooting Star" },
		{ emoji: "🌌", name: "Milky Way" },
		{ emoji: "🌉", name: "Bridge at Night" },
		{ emoji: "🌁", name: "Foggy" },
		{ emoji: "⭐", name: "Star" },
		{ emoji: "💫", name: "Dizzy" },
		{ emoji: "✨", name: "Sparkles" },
		{ emoji: "☄️", name: "Comet" },
		{ emoji: "🌏", name: "Globe Showing Asia-Australia" },
		{ emoji: "🌎", name: "Globe Showing Americas" },
		{ emoji: "🌍", name: "Globe Showing Europe-Africa" },
	],

	animals: [
		{ emoji: "🦄", name: "Unicorn" },
		{ emoji: "🐱", name: "Cat Face" },
		{ emoji: "🐶", name: "Dog Face" },
		{ emoji: "🦊", name: "Fox" },
		{ emoji: "🐼", name: "Panda" },
		{ emoji: "🦁", name: "Lion" },
		{ emoji: "🐨", name: "Koala" },
		{ emoji: "🦋", name: "Butterfly" },
		{ emoji: "🐝", name: "Honeybee" },
		{ emoji: "🐢", name: "Turtle" },
		{ emoji: "🦉", name: "Owl" },
		{ emoji: "🐧", name: "Penguin" },
		{ emoji: "🐸", name: "Frog" },
		{ emoji: "🦆", name: "Duck" },
		{ emoji: "🐰", name: "Rabbit Face" },
		{ emoji: "🦔", name: "Hedgehog" },
		{ emoji: "🐙", name: "Octopus" },
		{ emoji: "🐚", name: "Spiral Shell" },
		{ emoji: "🦞", name: "Lobster" },
		{ emoji: "🦐", name: "Shrimp" },
		{ emoji: "🐌", name: "Snail" },
		{ emoji: "🦗", name: "Cricket" },
		{ emoji: "🐛", name: "Bug" },
		{ emoji: "🦟", name: "Mosquito" },
		{ emoji: "🐜", name: "Ant" },
		{ emoji: "🕷️", name: "Spider" },
		{ emoji: "🕸️", name: "Spider Web" },
		{ emoji: "🦂", name: "Scorpion" },
		{ emoji: "🦠", name: "Microbe" },
		{ emoji: "🐉", name: "Dragon" },
		{ emoji: "🦕", name: "Sauropod" },
		{ emoji: "🦖", name: "T-Rex" },
		{ emoji: "🐅", name: "Tiger" },
		{ emoji: "🦒", name: "Giraffe" },
		{ emoji: "🦓", name: "Zebra" },
		{ emoji: "🦣", name: "Mammoth" },
		{ emoji: "🐘", name: "Elephant" },
		{ emoji: "🦏", name: "Rhinoceros" },
		{ emoji: "🦛", name: "Hippopotamus" },
		{ emoji: "🐪", name: "Camel" },
		{ emoji: "🦙", name: "Llama" },
		{ emoji: "🐫", name: "Two-Hump Camel" },
		{ emoji: "🦌", name: "Deer" },
		{ emoji: "🐎", name: "Horse" },
		{ emoji: "🦬", name: "Bison" },
		{ emoji: "🐄", name: "Cow" },
		{ emoji: "🐂", name: "Ox" },
		{ emoji: "🐃", name: "Water Buffalo" },
		{ emoji: "🐏", name: "Ram" },
		{ emoji: "🐑", name: "Ewe" },
		{ emoji: "🐐", name: "Goat" },
		{ emoji: "🐕", name: "Dog" },
		{ emoji: "🐩", name: "Poodle" },
		{ emoji: "🐈", name: "Cat" },
		{ emoji: "🐈‍⬛", name: "Black Cat" },
		{ emoji: "🐓", name: "Rooster" },
		{ emoji: "🐔", name: "Chicken" },
		{ emoji: "🐤", name: "Baby Chick" },
		{ emoji: "🐣", name: "Hatching Chick" },
		{ emoji: "🐥", name: "Front-Facing Baby Chick" },
		{ emoji: "🐦", name: "Bird" },
		{ emoji: "🦅", name: "Eagle" },
		{ emoji: "🦢", name: "Swan" },
		{ emoji: "🦤", name: "Dodo" },
		{ emoji: "🦩", name: "Flamingo" },
		{ emoji: "🦚", name: "Peacock" },
		{ emoji: "🦜", name: "Parrot" },
		{ emoji: "🦭", name: "Seal" },
		{ emoji: "🦎", name: "Lizard" },
		{ emoji: "🐍", name: "Snake" },
		{ emoji: "🐊", name: "Crocodile" },
		{ emoji: "🐢", name: "Turtle" },
		{ emoji: "🦀", name: "Crab" },
		{ emoji: "🐠", name: "Tropical Fish" },
		{ emoji: "🐟", name: "Fish" },
		{ emoji: "🦈", name: "Shark" },
		{ emoji: "🐬", name: "Dolphin" },
		{ emoji: "🐳", name: "Whale" },
		{ emoji: "🦑", name: "Squid" },
		{ emoji: "🐋", name: "Whale" },
		{ emoji: "🦭", name: "Seal" },
		{ emoji: "🐅", name: "Tiger" },
		{ emoji: "🐆", name: "Leopard" },
		{ emoji: "🦓", name: "Zebra" },
		{ emoji: "🦍", name: "Gorilla" },
		{ emoji: "🦧", name: "Orangutan" },
		{ emoji: "🐒", name: "Monkey" },
		{ emoji: "🐵", name: "Monkey Face" },
		{ emoji: "🙈", name: "See-No-Evil Monkey" },
		{ emoji: "🙉", name: "Hear-No-Evil Monkey" },
		{ emoji: "🙊", name: "Speak-No-Evil Monkey" },
		{ emoji: "🐗", name: "Boar" },
		{ emoji: "🐖", name: "Pig" },
		{ emoji: "🐷", name: "Pig Face" },
		{ emoji: "🐽", name: "Pig Nose" },
		{ emoji: "🐺", name: "Wolf" },
		{ emoji: "🦝", name: "Raccoon" },
		{ emoji: "🦡", name: "Badger" },
		{ emoji: "🦨", name: "Skunk" },
		{ emoji: "🦦", name: "Otter" },
		{ emoji: "🦥", name: "Sloth" },
		{ emoji: "🦘", name: "Kangaroo" },
		{ emoji: "🦫", name: "Beaver" },
	],

	food: [
		{ emoji: "🍕", name: "Pizza" },
		{ emoji: "🍔", name: "Hamburger" },
		{ emoji: "🍦", name: "Ice Cream" },
		{ emoji: "🍩", name: "Doughnut" },
		{ emoji: "🍰", name: "Shortcake" },
		{ emoji: "🍓", name: "Strawberry" },
		{ emoji: "🍉", name: "Watermelon" },
		{ emoji: "🍌", name: "Banana" },
		{ emoji: "🍒", name: "Cherries" },
		{ emoji: "🍇", name: "Grapes" },
		{ emoji: "🥝", name: "Kiwi Fruit" },
		{ emoji: "🍑", name: "Peach" },
		{ emoji: "🥕", name: "Carrot" },
		{ emoji: "🌽", name: "Corn" },
		{ emoji: "🥑", name: "Avocado" },
		{ emoji: "🍅", name: "Tomato" },
		{ emoji: "🥒", name: "Cucumber" },
		{ emoji: "🌶️", name: "Hot Pepper" },
		{ emoji: "🥦", name: "Broccoli" },
		{ emoji: "🧄", name: "Garlic" },
		{ emoji: "🥔", name: "Potato" },
		{ emoji: "🧅", name: "Onion" },
		{ emoji: "🥬", name: "Leafy Green" },
		{ emoji: "🫑", name: "Bell Pepper" },
		{ emoji: "🍆", name: "Eggplant" },
		{ emoji: "🥗", name: "Green Salad" },
		{ emoji: "🥙", name: "Stuffed Flatbread" },
		{ emoji: "🌮", name: "Taco" },
		{ emoji: "🌯", name: "Burrito" },
		{ emoji: "🥪", name: "Sandwich" },
		{ emoji: "🍱", name: "Bento Box" },
		{ emoji: "🍜", name: "Steaming Bowl" },
		{ emoji: "🍝", name: "Spaghetti" },
		{ emoji: "🍛", name: "Curry Rice" },
		{ emoji: "🍲", name: "Pot of Food" },
		{ emoji: "🍣", name: "Sushi" },
		{ emoji: "🍤", name: "Fried Shrimp" },
		{ emoji: "🥟", name: "Dumpling" },
		{ emoji: "🥠", name: "Fortune Cookie" },
		{ emoji: "🥡", name: "Takeout Box" },
		{ emoji: "🍥", name: "Fish Cake" },
		{ emoji: "🥮", name: "Moon Cake" },
		{ emoji: "🍡", name: "Dango" },
		{ emoji: "🍢", name: "Oden" },
		{ emoji: "🍧", name: "Shaved Ice" },
		{ emoji: "🍨", name: "Ice Cream" },
		{ emoji: "🍭", name: "Lollipop" },
		{ emoji: "🍮", name: "Custard" },
		{ emoji: "🍪", name: "Cookie" },
		{ emoji: "🎂", name: "Birthday Cake" },
		{ emoji: "🧁", name: "Cupcake" },
		{ emoji: "🥧", name: "Pie" },
		{ emoji: "🍫", name: "Chocolate Bar" },
		{ emoji: "🍬", name: "Candy" },
		{ emoji: "🍯", name: "Honey Pot" },
		{ emoji: "🍼", name: "Baby Bottle" },
		{ emoji: "🥛", name: "Glass of Milk" },
		{ emoji: "☕", name: "Hot Beverage" },
		{ emoji: "🍵", name: "Teacup Without Handle" },
		{ emoji: "🍶", name: "Sake" },
		{ emoji: "🍾", name: "Bottle with Popping Cork" },
		{ emoji: "🍷", name: "Wine Glass" },
		{ emoji: "🍸", name: "Cocktail Glass" },
		{ emoji: "🍹", name: "Tropical Drink" },
		{ emoji: "🍺", name: "Beer Mug" },
		{ emoji: "🍻", name: "Clinking Beer Mugs" },
		{ emoji: "🥂", name: "Clinking Glasses" },
		{ emoji: "🥃", name: "Tumbler Glass" },
		{ emoji: "🥤", name: "Cup with Straw" },
		{ emoji: "🧃", name: "Beverage Box" },
		{ emoji: "🧉", name: "Mate" },
		{ emoji: "🧊", name: "Ice" },
		{ emoji: "🥄", name: "Spoon" },
		{ emoji: "🍴", name: "Fork and Knife" },
		{ emoji: "🥢", name: "Chopsticks" },
		{ emoji: "🍞", name: "Bread" },
		{ emoji: "🥐", name: "Croissant" },
		{ emoji: "🥖", name: "Baguette Bread" },
		{ emoji: "🥨", name: "Pretzel" },
		{ emoji: "🥯", name: "Bagel" },
		{ emoji: "🥞", name: "Pancakes" },
		{ emoji: "🧇", name: "Waffle" },
		{ emoji: "🧀", name: "Cheese Wedge" },
		{ emoji: "🍖", name: "Meat on Bone" },
		{ emoji: "🍗", name: "Poultry Leg" },
		{ emoji: "🥩", name: "Cut of Meat" },
		{ emoji: "🥓", name: "Bacon" },
		{ emoji: "🍟", name: "French Fries" },
		{ emoji: "🍿", name: "Popcorn" },
		{ emoji: "🧂", name: "Salt" },
		{ emoji: "🥚", name: "Egg" },
		{ emoji: "🍳", name: "Cooking" },
		{ emoji: "🥘", name: "Shallow Pan of Food" },
		{ emoji: "🥫", name: "Canned Food" },
		{ emoji: "🫘", name: "Beans" },
		{ emoji: "🍠", name: "Roasted Sweet Potato" },
		{ emoji: "🥜", name: "Peanuts" },
		{ emoji: "🫛", name: "Pea Pod" },
		{ emoji: "🌰", name: "Chestnut" },
		{ emoji: "🍈", name: "Melon" },
		{ emoji: "🍐", name: "Pear" },
		{ emoji: "🍏", name: "Green Apple" },
		{ emoji: "🍎", name: "Red Apple" },
		{ emoji: "🍋", name: "Lemon" },
		{ emoji: "🍊", name: "Tangerine" },
		{ emoji: "🍍", name: "Pineapple" },
		{ emoji: "🥥", name: "Coconut" },
		{ emoji: "🥭", name: "Mango" },
		{ emoji: "🫐", name: "Blueberries" },
	],

	sports: [
		{ emoji: "⚽", name: "Soccer Ball" },
		{ emoji: "🏀", name: "Basketball" },
		{ emoji: "🏈", name: "Football" },
		{ emoji: "⚾", name: "Baseball" },
		{ emoji: "🎾", name: "Tennis" },
		{ emoji: "🏐", name: "Volleyball" },
		{ emoji: "🏓", name: "Ping Pong" },
		{ emoji: "🏸", name: "Badminton" },
		{ emoji: "🥊", name: "Boxing Glove" },
		{ emoji: "🏹", name: "Bow and Arrow" },
		{ emoji: "🎿", name: "Skis" },
		{ emoji: "🏂", name: "Snowboarder" },
		{ emoji: "⛷️", name: "Skier" },
		{ emoji: "🏊", name: "Person Swimming" },
		{ emoji: "🚴", name: "Person Biking" },
		{ emoji: "🏃", name: "Person Running" },
		{ emoji: "⛹️", name: "Person Bouncing Ball" },
		{ emoji: "🤸", name: "Person Cartwheeling" },
		{ emoji: "🧘", name: "Person in Lotus Position" },
		{ emoji: "🏋️", name: "Person Lifting Weights" },
		{ emoji: "🤾", name: "Person Playing Handball" },
		{ emoji: "🤺", name: "Person Fencing" },
		{ emoji: "🏇", name: "Horse Racing" },
		{ emoji: "⛳", name: "Flag in Hole" },
		{ emoji: "🎣", name: "Fishing Pole" },
		{ emoji: "🏏", name: "Cricket Game" },
		{ emoji: "🏑", name: "Field Hockey" },
		{ emoji: "🏒", name: "Ice Hockey" },
		{ emoji: "🥅", name: "Goal Net" },
		{ emoji: "🎳", name: "Bowling" },
		{ emoji: "🏹", name: "Bow and Arrow" },
		{ emoji: "🥍", name: "Lacrosse" },
		{ emoji: "🛹", name: "Skateboard" },
		{ emoji: "🛼", name: "Roller Skate" },
		{ emoji: "🛷", name: "Sled" },
		{ emoji: "🥌", name: "Curling Stone" },
		{ emoji: "🎽", name: "Running Shirt" },
		{ emoji: "🥋", name: "Martial Arts Uniform" },
		{ emoji: "🥏", name: "Flying Disc" },
		{ emoji: "🪃", name: "Boomerang" },
		{ emoji: "🪁", name: "Kite" },
	],

	places: [
		{ emoji: "🏟️", name: "Stadium" },
		{ emoji: "🏛️", name: "Classical Building" },
		{ emoji: "🏗️", name: "Building Construction" },
		{ emoji: "🧱", name: "Brick" },
		{ emoji: "🪨", name: "Rock" },
		{ emoji: "🪵", name: "Wood" },
		{ emoji: "🛖", name: "Hut" },
		{ emoji: "🏘️", name: "Houses" },
		{ emoji: "🏚️", name: "Derelict House" },
		{ emoji: "🏠", name: "House" },
		{ emoji: "🏡", name: "House with Garden" },
		{ emoji: "🏢", name: "Office Building" },
		{ emoji: "🏣", name: "Japanese Post Office" },
		{ emoji: "🏤", name: "Post Office" },
		{ emoji: "🏥", name: "Hospital" },
		{ emoji: "🏦", name: "Bank" },
		{ emoji: "🏨", name: "Hotel" },
		{ emoji: "🏩", name: "Love Hotel" },
		{ emoji: "🏪", name: "Convenience Store" },
		{ emoji: "🏫", name: "School" },
		{ emoji: "🏬", name: "Department Store" },
		{ emoji: "🏭", name: "Factory" },
		{ emoji: "🏯", name: "Japanese Castle" },
		{ emoji: "🏰", name: "Castle" },
		{ emoji: "💒", name: "Wedding" },
		{ emoji: "🗼", name: "Tokyo Tower" },
		{ emoji: "🗽", name: "Statue of Liberty" },
		{ emoji: "⛪", name: "Church" },
		{ emoji: "🕌", name: "Mosque" },
		{ emoji: "🛕", name: "Hindu Temple" },
		{ emoji: "🕍", name: "Synagogue" },
		{ emoji: "⛩️", name: "Shinto Shrine" },
		{ emoji: "🕋", name: "Kaaba" },
		{ emoji: "⛲", name: "Fountain" },
		{ emoji: "⛺", name: "Tent" },
		{ emoji: "🌁", name: "Foggy" },
		{ emoji: "🌃", name: "Night with Stars" },
		{ emoji: "🏙️", name: "Cityscape" },
		{ emoji: "🌆", name: "Cityscape at Dusk" },
		{ emoji: "🌇", name: "Sunset" },
		{ emoji: "🌉", name: "Bridge at Night" },
		{ emoji: "🎠", name: "Carousel Horse" },
		{ emoji: "🎡", name: "Ferris Wheel" },
		{ emoji: "🎢", name: "Roller Coaster" },
		{ emoji: "🚂", name: "Locomotive" },
		{ emoji: "🚃", name: "Railway Car" },
		{ emoji: "🚄", name: "High-Speed Train" },
		{ emoji: "🚅", name: "Bullet Train" },
		{ emoji: "🚆", name: "Train" },
		{ emoji: "🚇", name: "Metro" },
		{ emoji: "🚈", name: "Light Rail" },
		{ emoji: "🚉", name: "Station" },
		{ emoji: "🚊", name: "Tram" },
		{ emoji: "🚝", name: "Monorail" },
		{ emoji: "🚞", name: "Mountain Railway" },
		{ emoji: "🚋", name: "Tram Car" },
		{ emoji: "🚌", name: "Bus" },
		{ emoji: "🚍", name: "Oncoming Bus" },
		{ emoji: "🚎", name: "Trolleybus" },
		{ emoji: "🚐", name: "Minibus" },
		{ emoji: "🚑", name: "Ambulance" },
		{ emoji: "🚒", name: "Fire Engine" },
		{ emoji: "🚓", name: "Police Car" },
		{ emoji: "🚔", name: "Oncoming Police Car" },
		{ emoji: "🚕", name: "Taxi" },
		{ emoji: "🚖", name: "Oncoming Taxi" },
		{ emoji: "🚗", name: "Automobile" },
		{ emoji: "🚘", name: "Oncoming Automobile" },
		{ emoji: "🚙", name: "Sport Utility Vehicle" },
		{ emoji: "🛻", name: "Pickup Truck" },
		{ emoji: "🚚", name: "Delivery Truck" },
		{ emoji: "🚛", name: "Articulated Lorry" },
		{ emoji: "🚜", name: "Tractor" },
		{ emoji: "🏎️", name: "Racing Car" },
		{ emoji: "🏍️", name: "Motorcycle" },
		{ emoji: "🛵", name: "Motor Scooter" },
		{ emoji: "🦽", name: "Manual Wheelchair" },
		{ emoji: "🦼", name: "Motorized Wheelchair" },
		{ emoji: "🛺", name: "Auto Rickshaw" },
		{ emoji: "🚲", name: "Bicycle" },
		{ emoji: "🛴", name: "Kick Scooter" },
		{ emoji: "🛹", name: "Skateboard" },
		{ emoji: "🛼", name: "Roller Skate" },
		{ emoji: "🚏", name: "Bus Stop" },
		{ emoji: "🛣️", name: "Motorway" },
		{ emoji: "🛤️", name: "Railway Track" },
		{ emoji: "⛽", name: "Fuel Pump" },
		{ emoji: "🚨", name: "Police Car Light" },
		{ emoji: "🚥", name: "Horizontal Traffic Light" },
		{ emoji: "🚦", name: "Vertical Traffic Light" },
		{ emoji: "🛑", name: "Stop Sign" },
		{ emoji: "🚧", name: "Construction" },
		{ emoji: "⚓", name: "Anchor" },
		{ emoji: "⛵", name: "Sailboat" },
		{ emoji: "🛶", name: "Canoe" },
		{ emoji: "🚤", name: "Speedboat" },
		{ emoji: "🛳️", name: "Passenger Ship" },
		{ emoji: "⛴️", name: "Ferry" },
		{ emoji: "🛥️", name: "Motor Boat" },
		{ emoji: "🚢", name: "Ship" },
		{ emoji: "✈️", name: "Airplane" },
		{ emoji: "🛩️", name: "Small Airplane" },
		{ emoji: "🛫", name: "Airplane Departure" },
		{ emoji: "🛬", name: "Airplane Arrival" },
		{ emoji: "🪂", name: "Parachute" },
		{ emoji: "💺", name: "Seat" },
		{ emoji: "🚁", name: "Helicopter" },
		{ emoji: "🚟", name: "Suspension Railway" },
		{ emoji: "🚠", name: "Mountain Cableway" },
		{ emoji: "🚡", name: "Aerial Tramway" },
		{ emoji: "🛰️", name: "Satellite" },
		{ emoji: "🚀", name: "Rocket" },
		{ emoji: "🛸", name: "Flying Saucer" },
	],

	symbols: [
		{ emoji: "❤️", name: "Red Heart" },
		{ emoji: "🧡", name: "Orange Heart" },
		{ emoji: "💛", name: "Yellow Heart" },
		{ emoji: "💚", name: "Green Heart" },
		{ emoji: "💙", name: "Blue Heart" },
		{ emoji: "💜", name: "Purple Heart" },
		{ emoji: "🖤", name: "Black Heart" },
		{ emoji: "🤍", name: "White Heart" },
		{ emoji: "🤎", name: "Brown Heart" },
		{ emoji: "💔", name: "Broken Heart" },
		{ emoji: "❣️", name: "Heart Exclamation" },
		{ emoji: "💕", name: "Two Hearts" },
		{ emoji: "💞", name: "Revolving Hearts" },
		{ emoji: "💓", name: "Beating Heart" },
		{ emoji: "💗", name: "Growing Heart" },
		{ emoji: "💖", name: "Sparkling Heart" },
		{ emoji: "💘", name: "Heart with Arrow" },
		{ emoji: "💝", name: "Heart with Ribbon" },
		{ emoji: "💟", name: "Heart Decoration" },
		{ emoji: "☮️", name: "Peace Symbol" },
		{ emoji: "✝️", name: "Latin Cross" },
		{ emoji: "☪️", name: "Star and Crescent" },
		{ emoji: "🕉️", name: "Om" },
		{ emoji: "☸️", name: "Wheel of Dharma" },
		{ emoji: "✡️", name: "Star of David" },
		{ emoji: "🔯", name: "Dotted Six-Pointed Star" },
		{ emoji: "🕎", name: "Menorah" },
		{ emoji: "☯️", name: "Yin Yang" },
		{ emoji: "☦️", name: "Orthodox Cross" },
		{ emoji: "🛐", name: "Place of Worship" },
		{ emoji: "⛎", name: "Ophiuchus" },
		{ emoji: "♈", name: "Aries" },
		{ emoji: "♉", name: "Taurus" },
		{ emoji: "♊", name: "Gemini" },
		{ emoji: "♋", name: "Cancer" },
		{ emoji: "♌", name: "Leo" },
		{ emoji: "♍", name: "Virgo" },
		{ emoji: "♎", name: "Libra" },
		{ emoji: "♏", name: "Scorpio" },
		{ emoji: "♐", name: "Sagittarius" },
		{ emoji: "♑", name: "Capricorn" },
		{ emoji: "♒", name: "Aquarius" },
		{ emoji: "♓", name: "Pisces" },
		{ emoji: "🆔", name: "ID Button" },
		{ emoji: "⚛️", name: "Atom Symbol" },
		{ emoji: "🔱", name: "Trident Emblem" },
		{ emoji: "📛", name: "Name Badge" },
		{ emoji: "⚠️", name: "Warning" },
		{ emoji: "🚸", name: "Children Crossing" },
		{ emoji: "⛔", name: "No Entry" },
		{ emoji: "🚫", name: "Prohibited" },
		{ emoji: "🚳", name: "No Bicycles" },
		{ emoji: "🚭", name: "No Smoking" },
		{ emoji: "🚯", name: "No Littering" },
		{ emoji: "🚱", name: "Non-Potable Water" },
		{ emoji: "🚷", name: "No Pedestrians" },
		{ emoji: "📵", name: "No Mobile Phones" },
		{ emoji: "🔞", name: "No One Under Eighteen" },
		{ emoji: "☢️", name: "Radioactive" },
		{ emoji: "☣️", name: "Biohazard" },
		{ emoji: "⬆️", name: "Up Arrow" },
		{ emoji: "↗️", name: "Up-Right Arrow" },
		{ emoji: "➡️", name: "Right Arrow" },
		{ emoji: "↘️", name: "Down-Right Arrow" },
		{ emoji: "⬇️", name: "Down Arrow" },
		{ emoji: "↙️", name: "Down-Left Arrow" },
		{ emoji: "⬅️", name: "Left Arrow" },
		{ emoji: "↖️", name: "Up-Left Arrow" },
		{ emoji: "↕️", name: "Up-Down Arrow" },
		{ emoji: "↔️", name: "Left-Right Arrow" },
		{ emoji: "↩️", name: "Right Arrow Curving Left" },
		{ emoji: "↪️", name: "Left Arrow Curving Right" },
		{ emoji: "⤴️", name: "Right Arrow Curving Up" },
		{ emoji: "⤵️", name: "Right Arrow Curving Down" },
		{ emoji: "🔃", name: "Clockwise Vertical Arrows" },
		{ emoji: "🔄", name: "Counterclockwise Arrows Button" },
		{ emoji: "🔙", name: "Back Arrow" },
		{ emoji: "🔚", name: "End Arrow" },
		{ emoji: "🔛", name: "On! Arrow" },
		{ emoji: "🔜", name: "Soon Arrow" },
		{ emoji: "🔝", name: "Top Arrow" },
		{ emoji: "✅", name: "Check Mark Button" },
		{ emoji: "☑️", name: "Check Box with Check" },
		{ emoji: "✔️", name: "Check Mark" },
		{ emoji: "✖️", name: "Multiplication Sign" },
		{ emoji: "❌", name: "Cross Mark" },
		{ emoji: "❎", name: "Cross Mark Button" },
		{ emoji: "➕", name: "Plus Sign" },
		{ emoji: "➖", name: "Minus Sign" },
		{ emoji: "➗", name: "Division Sign" },
		{ emoji: "♾️", name: "Infinity" },
		{ emoji: "💲", name: "Heavy Dollar Sign" },
		{ emoji: "💱", name: "Currency Exchange" },
		{ emoji: "™️", name: "Trade Mark" },
		{ emoji: "©️", name: "Copyright" },
		{ emoji: "®️", name: "Registered" },
		{ emoji: "〰️", name: "Wavy Dash" },
		{ emoji: "➰", name: "Curly Loop" },
		{ emoji: "➿", name: "Double Curly Loop" },
		{ emoji: "🔚", name: "END Arrow" },
		{ emoji: "🔙", name: "BACK Arrow" },
		{ emoji: "🔛", name: "ON! Arrow" },
		{ emoji: "🔝", name: "TOP Arrow" },
		{ emoji: "🔜", name: "SOON Arrow" },
		{ emoji: "✳️", name: "Eight-Spoked Asterisk" },
		{ emoji: "✴️", name: "Eight-Pointed Star" },
		{ emoji: "❇️", name: "Sparkle" },
		{ emoji: "‼️", name: "Double Exclamation Mark" },
		{ emoji: "⁉️", name: "Exclamation Question Mark" },
		{ emoji: "❓", name: "Question Mark" },
		{ emoji: "❔", name: "White Question Mark" },
		{ emoji: "❕", name: "White Exclamation Mark" },
		{ emoji: "❗", name: "Exclamation Mark" },
		{ emoji: "〽️", name: "Part Alternation Mark" },
		{ emoji: "⚕️", name: "Medical Symbol" },
		{ emoji: "♻️", name: "Recycling Symbol" },
		{ emoji: "⚜️", name: "Fleur-de-lis" },
		{ emoji: "🔱", name: "Trident Emblem" },
		{ emoji: "📛", name: "Name Badge" },
		{ emoji: "🔰", name: "Japanese Symbol for Beginner" },
		{ emoji: "⭕", name: "Hollow Red Circle" },
		{ emoji: "✅", name: "Check Mark Button" },
		{ emoji: "☑️", name: "Check Box with Check" },
		{ emoji: "✔️", name: "Check Mark" },
		{ emoji: "❌", name: "Cross Mark" },
		{ emoji: "❎", name: "Cross Mark Button" },
		{ emoji: "➰", name: "Curly Loop" },
		{ emoji: "➿", name: "Double Curly Loop" },
		{ emoji: "〽️", name: "Part Alternation Mark" },
		{ emoji: "✳️", name: "Eight-Spoked Asterisk" },
		{ emoji: "✴️", name: "Eight-Pointed Star" },
		{ emoji: "❇️", name: "Sparkle" },
		{ emoji: "💠", name: "Diamond with a Dot" },
		{ emoji: "🔘", name: "Radio Button" },
		{ emoji: "🔳", name: "White Square Button" },
		{ emoji: "🔲", name: "Black Square Button" },
		{ emoji: "🏁", name: "Chequered Flag" },
		{ emoji: "🚩", name: "Triangular Flag" },
		{ emoji: "🎌", name: "Crossed Flags" },
		{ emoji: "🏴", name: "Black Flag" },
		{ emoji: "🏳️", name: "White Flag" },
		{ emoji: "🏳️‍🌈", name: "Rainbow Flag" },
	],

	people: [
		{ emoji: "😀", name: "Grinning Face" },
		{ emoji: "😎", name: "Smiling Face with Sunglasses" },
		{ emoji: "🤩", name: "Star-Struck" },
		{ emoji: "🥳", name: "Partying Face" },
		{ emoji: "😇", name: "Smiling Face with Halo" },
		{ emoji: "🤓", name: "Nerd Face" },
		{ emoji: "🧐", name: "Face with Monocle" },
		{ emoji: "🤠", name: "Cowboy Hat Face" },
		{ emoji: "🥸", name: "Disguised Face" },
		{ emoji: "😺", name: "Grinning Cat" },
		{ emoji: "😸", name: "Grinning Cat with Smiling Eyes" },
		{ emoji: "😻", name: "Smiling Cat with Heart-Eyes" },
		{ emoji: "💀", name: "Skull" },
		{ emoji: "👻", name: "Ghost" },
		{ emoji: "👽", name: "Alien" },
		{ emoji: "🤖", name: "Robot" },
		{ emoji: "💩", name: "Pile of Poo" },
		{ emoji: "👋", name: "Waving Hand" },
		{ emoji: "🤚", name: "Raised Back of Hand" },
		{ emoji: "🖐️", name: "Hand with Fingers Splayed" },
		{ emoji: "✋", name: "Raised Hand" },
		{ emoji: "🖖", name: "Vulcan Salute" },
		{ emoji: "👌", name: "OK Hand" },
		{ emoji: "🤌", name: "Pinched Fingers" },
		{ emoji: "🤏", name: "Pinching Hand" },
		{ emoji: "✌️", name: "Victory Hand" },
		{ emoji: "🤞", name: "Crossed Fingers" },
		{ emoji: "🤟", name: "Love-You Gesture" },
		{ emoji: "🤘", name: "Sign of the Horns" },
		{ emoji: "🤙", name: "Call Me Hand" },
		{ emoji: "👈", name: "Backhand Index Pointing Left" },
		{ emoji: "👉", name: "Backhand Index Pointing Right" },
		{ emoji: "👆", name: "Backhand Index Pointing Up" },
		{ emoji: "🖕", name: "Middle Finger" },
		{ emoji: "👇", name: "Backhand Index Pointing Down" },
		{ emoji: "☝️", name: "Index Pointing Up" },
		{ emoji: "👍", name: "Thumbs Up" },
		{ emoji: "👎", name: "Thumbs Down" },
		{ emoji: "✊", name: "Raised Fist" },
		{ emoji: "👊", name: "Oncoming Fist" },
		{ emoji: "🤛", name: "Left-Facing Fist" },
		{ emoji: "🤜", name: "Right-Facing Fist" },
		{ emoji: "👏", name: "Clapping Hands" },
		{ emoji: "🙌", name: "Raising Hands" },
		{ emoji: "👐", name: "Open Hands" },
		{ emoji: "🤲", name: "Palms Up Together" },
		{ emoji: "🤝", name: "Handshake" },
		{ emoji: "🙏", name: "Folded Hands" },
		{ emoji: "💅", name: "Nail Polish" },
		{ emoji: "🤳", name: "Selfie" },
		{ emoji: "💪", name: "Flexed Biceps" },
		{ emoji: "🦾", name: "Mechanical Arm" },
		{ emoji: "🦿", name: "Mechanical Leg" },
		{ emoji: "🦵", name: "Leg" },
		{ emoji: "🦶", name: "Foot" },
		{ emoji: "👂", name: "Ear" },
		{ emoji: "🦻", name: "Ear with Hearing Aid" },
		{ emoji: "👃", name: "Nose" },
		{ emoji: "🧠", name: "Brain" },
		{ emoji: "🫀", name: "Anatomical Heart" },
		{ emoji: "🫁", name: "Lungs" },
		{ emoji: "🦷", name: "Tooth" },
		{ emoji: "🦴", name: "Bone" },
		{ emoji: "👀", name: "Eyes" },
		{ emoji: "👁️", name: "Eye" },
		{ emoji: "👅", name: "Tongue" },
		{ emoji: "👄", name: "Mouth" },
		{ emoji: "👶", name: "Baby" },
		{ emoji: "🧒", name: "Child" },
		{ emoji: "👦", name: "Boy" },
		{ emoji: "👧", name: "Girl" },
		{ emoji: "🧑", name: "Person" },
		{ emoji: "👱", name: "Person: Blond Hair" },
		{ emoji: "👨", name: "Man" },
		{ emoji: "🧔", name: "Person: Beard" },
		{ emoji: "👩", name: "Woman" },
		{ emoji: "🧓", name: "Older Person" },
		{ emoji: "👴", name: "Old Man" },
		{ emoji: "👵", name: "Old Woman" },
	],

	clothing: [
		{ emoji: "👗", name: "Dress" },
		{ emoji: "👔", name: "Necktie" },
		{ emoji: "👕", name: "T-Shirt" },
		{ emoji: "👖", name: "Jeans" },
		{ emoji: "🧥", name: "Coat" },
		{ emoji: "🧦", name: "Socks" },
		{ emoji: "👘", name: "Kimono" },
		{ emoji: "🥻", name: "Sari" },
		{ emoji: "🩱", name: "One-Piece Swimsuit" },
		{ emoji: "🩲", name: "Briefs" },
		{ emoji: "🩳", name: "Shorts" },
		{ emoji: "👙", name: "Bikini" },
		{ emoji: "👚", name: "Woman's Clothes" },
		{ emoji: "👛", name: "Purse" },
		{ emoji: "👜", name: "Handbag" },
		{ emoji: "👝", name: "Clutch Bag" },
		{ emoji: "🎒", name: "Backpack" },
		{ emoji: "🩴", name: "Thong Sandal" },
		{ emoji: "👞", name: "Man's Shoe" },
		{ emoji: "👟", name: "Running Shoe" },
		{ emoji: "🥾", name: "Hiking Boot" },
		{ emoji: "🥿", name: "Flat Shoe" },
		{ emoji: "👠", name: "High-Heeled Shoe" },
		{ emoji: "👡", name: "Woman's Sandal" },
		{ emoji: "🩰", name: "Ballet Shoes" },
		{ emoji: "👢", name: "Woman's Boot" },
		{ emoji: "👑", name: "Crown" },
		{ emoji: "👒", name: "Woman's Hat" },
		{ emoji: "🎩", name: "Top Hat" },
		{ emoji: "🎓", name: "Graduation Cap" },
		{ emoji: "🧢", name: "Billed Cap" },
		{ emoji: "🪖", name: "Military Helmet" },
		{ emoji: "⛑️", name: "Rescue Worker's Helmet" },
		{ emoji: "💄", name: "Lipstick" },
		{ emoji: "💍", name: "Ring" },
		{ emoji: "💎", name: "Gem Stone" },
		{ emoji: "🔇", name: "Muted Speaker" },
		{ emoji: "🔈", name: "Speaker Low Volume" },
		{ emoji: "🔉", name: "Speaker Medium Volume" },
		{ emoji: "🔊", name: "Speaker High Volume" },
		{ emoji: "📢", name: "Loudspeaker" },
		{ emoji: "📣", name: "Megaphone" },
		{ emoji: "🔔", name: "Bell" },
		{ emoji: "🔕", name: "Bell with Slash" },
		{ emoji: "🎼", name: "Musical Score" },
		{ emoji: "🎵", name: "Musical Note" },
		{ emoji: "🎶", name: "Musical Notes" },
		{ emoji: "🎙️", name: "Studio Microphone" },
		{ emoji: "🎚️", name: "Level Slider" },
		{ emoji: "🎛️", name: "Control Knobs" },
		{ emoji: "🎤", name: "Microphone" },
		{ emoji: "🎧", name: "Headphone" },
		{ emoji: "📻", name: "Radio" },
		{ emoji: "🎷", name: "Saxophone" },
		{ emoji: "🪗", name: "Accordion" },
		{ emoji: "🎸", name: "Guitar" },
		{ emoji: "🎹", name: "Musical Keyboard" },
		{ emoji: "🎺", name: "Trumpet" },
		{ emoji: "🎻", name: "Violin" },
		{ emoji: "🪕", name: "Banjo" },
		{ emoji: "🥁", name: "Drum" },
		{ emoji: "🪘", name: "Long Drum" },
	],

	misc: [
		{ emoji: "🎭", name: "Performing Arts" },
		{ emoji: "🎪", name: "Circus Tent" },
		{ emoji: "🎨", name: "Artist Palette" },
		{ emoji: "🧩", name: "Puzzle Piece" },
		{ emoji: "🧸", name: "Teddy Bear" },
		{ emoji: "🪢", name: "Knot" },
		{ emoji: "🧿", name: "Nazar Amulet" },
		{ emoji: "🪬", name: "Hamsa" },
		{ emoji: "🔮", name: "Crystal Ball" },
		{ emoji: "🪄", name: "Magic Wand" },
		{ emoji: "🎈", name: "Balloon" },
		{ emoji: "🎆", name: "Fireworks" },
		{ emoji: "🎇", name: "Sparkler" },
		{ emoji: "🧨", name: "Firecracker" },
		{ emoji: "✨", name: "Sparkles" },
		{ emoji: "🎀", name: "Ribbon" },
		{ emoji: "🎁", name: "Wrapped Gift" },
		{ emoji: "🎗️", name: "Reminder Ribbon" },
		{ emoji: "🎟️", name: "Admission Tickets" },
		{ emoji: "🎫", name: "Ticket" },
		{ emoji: "🎖️", name: "Military Medal" },
		{ emoji: "🏆", name: "Trophy" },
		{ emoji: "🏅", name: "Sports Medal" },
		{ emoji: "🥇", name: "1st Place Medal" },
		{ emoji: "🥈", name: "2nd Place Medal" },
		{ emoji: "🥉", name: "3rd Place Medal" },
		{ emoji: "🌡️", name: "Thermometer" },
		{ emoji: "🧪", name: "Test Tube" },
		{ emoji: "🧫", name: "Petri Dish" },
		{ emoji: "🧬", name: "DNA" },
		{ emoji: "🔭", name: "Telescope" },
		{ emoji: "🔬", name: "Microscope" },
		{ emoji: "🕳️", name: "Hole" },
		{ emoji: "🩹", name: "Adhesive Bandage" },
		{ emoji: "🩺", name: "Stethoscope" },
		{ emoji: "💊", name: "Pill" },
		{ emoji: "💉", name: "Syringe" },
		{ emoji: "🩸", name: "Drop of Blood" },
		{ emoji: "�", name: "Microbe" },
		{ emoji: "🧲", name: "Magnet" },
		{ emoji: "🧰", name: "Toolbox" },
		{ emoji: "🧱", name: "Brick" },
		{ emoji: "🪜", name: "Ladder" },
		{ emoji: "🪛", name: "Screwdriver" },
		{ emoji: "🪚", name: "Carpentry Saw" },
		{ emoji: "🔧", name: "Wrench" },
		{ emoji: "🔨", name: "Hammer" },
		{ emoji: "⚒️", name: "Hammer and Pick" },
		{ emoji: "🛠️", name: "Hammer and Wrench" },
		{ emoji: "⛏️", name: "Pick" },
		{ emoji: "⚙️", name: "Gear" },
		{ emoji: "🗜️", name: "Clamp" },
		{ emoji: "⚖️", name: "Balance Scale" },
		{ emoji: "🦯", name: "White Cane" },
		{ emoji: "🔗", name: "Link" },
		{ emoji: "⛓️", name: "Chains" },
		{ emoji: "🪝", name: "Hook" },
		{ emoji: "🧯", name: "Fire Extinguisher" },
		{ emoji: "🛒", name: "Shopping Cart" },
		{ emoji: "🚬", name: "Cigarette" },
		{ emoji: "⚰️", name: "Coffin" },
		{ emoji: "🪦", name: "Headstone" },
		{ emoji: "⚱️", name: "Funeral Urn" },
		{ emoji: "🗿", name: "Moai" },
		{ emoji: "🪧", name: "Placard" },
	],

	emotions: [
		{ emoji: "😃", name: "Grinning Face with Big Eyes" },
		{ emoji: "😄", name: "Grinning Face with Smiling Eyes" },
		{ emoji: "😁", name: "Beaming Face with Smiling Eyes" },
		{ emoji: "😆", name: "Grinning Squinting Face" },
		{ emoji: "😅", name: "Grinning Face with Sweat" },
		{ emoji: "🤣", name: "Rolling on the Floor Laughing" },
		{ emoji: "😂", name: "Face with Tears of Joy" },
		{ emoji: "🙂", name: "Slightly Smiling Face" },
		{ emoji: "🙃", name: "Upside-Down Face" },
		{ emoji: "😉", name: "Winking Face" },
		{ emoji: "😊", name: "Smiling Face with Smiling Eyes" },
		{ emoji: "😋", name: "Face Savoring Food" },
		{ emoji: "😌", name: "Relieved Face" },
		{ emoji: "😍", name: "Smiling Face with Heart-Eyes" },
		{ emoji: "🥰", name: "Smiling Face with Hearts" },
		{ emoji: "😘", name: "Face Blowing a Kiss" },
		{ emoji: "😗", name: "Kissing Face" },
		{ emoji: "😙", name: "Kissing Face with Smiling Eyes" },
		{ emoji: "😚", name: "Kissing Face with Closed Eyes" },
		{ emoji: "☺️", name: "Smiling Face" },
		{ emoji: "🤗", name: "Hugging Face" },
		{ emoji: "🤩", name: "Star-Struck" },
		{ emoji: "🤔", name: "Thinking Face" },
		{ emoji: "🤨", name: "Face with Raised Eyebrow" },
		{ emoji: "😐", name: "Neutral Face" },
		{ emoji: "😑", name: "Expressionless Face" },
		{ emoji: "😶", name: "Face Without Mouth" },
		{ emoji: "🙄", name: "Face with Rolling Eyes" },
		{ emoji: "😏", name: "Smirking Face" },
		{ emoji: "😣", name: "Persevering Face" },
		{ emoji: "😥", name: "Sad but Relieved Face" },
		{ emoji: "😮", name: "Face with Open Mouth" },
		{ emoji: "🤐", name: "Zipper-Mouth Face" },
		{ emoji: "😯", name: "Hushed Face" },
		{ emoji: "😪", name: "Sleepy Face" },
		{ emoji: "😫", name: "Tired Face" },
		{ emoji: "🥱", name: "Yawning Face" },
		{ emoji: "😴", name: "Sleeping Face" },
		{ emoji: "😌", name: "Relieved Face" },
		{ emoji: "😛", name: "Face with Tongue" },
		{ emoji: "😜", name: "Winking Face with Tongue" },
		{ emoji: "😝", name: "Squinting Face with Tongue" },
		{ emoji: "🤤", name: "Drooling Face" },
		{ emoji: "😒", name: "Unamused Face" },
		{ emoji: "😓", name: "Downcast Face with Sweat" },
		{ emoji: "😔", name: "Pensive Face" },
		{ emoji: "😕", name: "Confused Face" },
		{ emoji: "🙁", name: "Slightly Frowning Face" },
		{ emoji: "☹️", name: "Frowning Face" },
		{ emoji: "😖", name: "Confounded Face" },
		{ emoji: "😞", name: "Disappointed Face" },
		{ emoji: "😟", name: "Worried Face" },
		{ emoji: "😤", name: "Face with Steam From Nose" },
		{ emoji: "😢", name: "Crying Face" },
		{ emoji: "😭", name: "Loudly Crying Face" },
		{ emoji: "😦", name: "Frowning Face with Open Mouth" },
		{ emoji: "😧", name: "Anguished Face" },
		{ emoji: "😨", name: "Fearful Face" },
		{ emoji: "😩", name: "Weary Face" },
		{ emoji: "🤯", name: "Exploding Head" },
		{ emoji: "😬", name: "Grimacing Face" },
		{ emoji: "😰", name: "Anxious Face with Sweat" },
		{ emoji: "😱", name: "Face Screaming in Fear" },
		{ emoji: "🥵", name: "Hot Face" },
		{ emoji: "🥶", name: "Cold Face" },
		{ emoji: "😳", name: "Flushed Face" },
		{ emoji: "🤪", name: "Zany Face" },
		{ emoji: "😵", name: "Face with Crossed-Out Eyes" },
		{ emoji: "🥴", name: "Woozy Face" },
		{ emoji: "😠", name: "Angry Face" },
		{ emoji: "😡", name: "Pouting Face" },
		{ emoji: "🤬", name: "Face with Symbols on Mouth" },
		{ emoji: "😷", name: "Face with Medical Mask" },
		{ emoji: "🤒", name: "Face with Thermometer" },
		{ emoji: "🤕", name: "Face with Head-Bandage" },
		{ emoji: "🤢", name: "Nauseated Face" },
		{ emoji: "🤮", name: "Face Vomiting" },
		{ emoji: "🤧", name: "Sneezing Face" },
		{ emoji: "🥺", name: "Pleading Face" },
		{ emoji: "😇", name: "Smiling Face with Halo" },
		{ emoji: "🤠", name: "Cowboy Hat Face" },
		{ emoji: "🤡", name: "Clown Face" },
		{ emoji: "🤥", name: "Lying Face" },
		{ emoji: "🤫", name: "Shushing Face" },
		{ emoji: "🤭", name: "Face with Hand Over Mouth" },
		{ emoji: "🧐", name: "Face with Monocle" },
		{ emoji: "🤓", name: "Nerd Face" },
		{ emoji: "😈", name: "Smiling Face with Horns" },
		{ emoji: "👿", name: "Angry Face with Horns" },
	],

	activities: [
		{ emoji: "🎯", name: "Direct Hit" },
		{ emoji: "🎪", name: "Circus Tent" },
		{ emoji: "🎭", name: "Performing Arts" },
		{ emoji: "🖼️", name: "Framed Picture" },
		{ emoji: "🎨", name: "Artist Palette" },
		{ emoji: "🧵", name: "Thread" },
		{ emoji: "🪡", name: "Sewing Needle" },
		{ emoji: "🧶", name: "Yarn" },
		{ emoji: "🎣", name: "Fishing Pole" },
		{ emoji: "🪝", name: "Hook" },
		{ emoji: "🎽", name: "Running Shirt" },
		{ emoji: "🥋", name: "Martial Arts Uniform" },
		{ emoji: "🎗️", name: "Reminder Ribbon" },
		{ emoji: "🏵️", name: "Rosette" },
		{ emoji: "🥏", name: "Flying Disc" },
		{ emoji: "🪃", name: "Boomerang" },
		{ emoji: "🪀", name: "Yo-Yo" },
		{ emoji: "🪁", name: "Kite" },
		{ emoji: "🎱", name: "Pool 8 Ball" },
		{ emoji: "🔮", name: "Crystal Ball" },
		{ emoji: "🪄", name: "Magic Wand" },
		{ emoji: "🧿", name: "Nazar Amulet" },
		{ emoji: "🎮", name: "Video Game" },
		{ emoji: "🕹️", name: "Joystick" },
		{ emoji: "🎰", name: "Slot Machine" },
		{ emoji: "🎲", name: "Game Die" },
		{ emoji: "🧩", name: "Puzzle Piece" },
		{ emoji: "🧸", name: "Teddy Bear" },
		{ emoji: "🪅", name: "Piñata" },
		{ emoji: "🪆", name: "Nesting Dolls" },
		{ emoji: "♠️", name: "Spade Suit" },
		{ emoji: "♥️", name: "Heart Suit" },
		{ emoji: "♦️", name: "Diamond Suit" },
		{ emoji: "♣️", name: "Club Suit" },
		{ emoji: "♟️", name: "Chess Pawn" },
		{ emoji: "🃏", name: "Joker" },
		{ emoji: "🀄", name: "Mahjong Red Dragon" },
		{ emoji: "🎴", name: "Flower Playing Cards" },
		{ emoji: "🎐", name: "Wind Chime" },
		{ emoji: "🎀", name: "Ribbon" },
		{ emoji: "🎁", name: "Wrapped Gift" },
		{ emoji: "🎊", name: "Confetti Ball" },
		{ emoji: "🎉", name: "Party Popper" },
		{ emoji: "🎈", name: "Balloon" },
		{ emoji: "🎏", name: "Carp Streamer" },
		{ emoji: "🎎", name: "Japanese Dolls" },
		{ emoji: "🏮", name: "Red Paper Lantern" },
		{ emoji: "🧧", name: "Red Envelope" },
	],

	tech: [
		{ emoji: "💻", name: "Laptop" },
		{ emoji: "🖥️", name: "Desktop Computer" },
		{ emoji: "🖨️", name: "Printer" },
		{ emoji: "⌨️", name: "Keyboard" },
		{ emoji: "🖱️", name: "Computer Mouse" },
		{ emoji: "🖲️", name: "Trackball" },
		{ emoji: "🕹️", name: "Joystick" },
		{ emoji: "🗜️", name: "Clamp" },
		{ emoji: "💾", name: "Floppy Disk" },
		{ emoji: "💿", name: "Optical Disk" },
		{ emoji: "📀", name: "DVD" },
		{ emoji: "📼", name: "Videocassette" },
		{ emoji: "📷", name: "Camera" },
		{ emoji: "📸", name: "Camera with Flash" },
		{ emoji: "📹", name: "Video Camera" },
		{ emoji: "🎥", name: "Movie Camera" },
		{ emoji: "📽️", name: "Film Projector" },
		{ emoji: "🎞️", name: "Film Frames" },
		{ emoji: "📞", name: "Telephone Receiver" },
		{ emoji: "☎️", name: "Telephone" },
		{ emoji: "📟", name: "Pager" },
		{ emoji: "📠", name: "Fax Machine" },
		{ emoji: "📺", name: "Television" },
		{ emoji: "📻", name: "Radio" },
		{ emoji: "🎙️", name: "Studio Microphone" },
		{ emoji: "🎚️", name: "Level Slider" },
		{ emoji: "🎛️", name: "Control Knobs" },
		{ emoji: "🧭", name: "Compass" },
		{ emoji: "⏱️", name: "Stopwatch" },
		{ emoji: "⏲️", name: "Timer Clock" },
		{ emoji: "⏰", name: "Alarm Clock" },
		{ emoji: "🕰️", name: "Mantelpiece Clock" },
		{ emoji: "⌛", name: "Hourglass Done" },
		{ emoji: "⏳", name: "Hourglass Not Done" },
		{ emoji: "📡", name: "Satellite Antenna" },
		{ emoji: "🔋", name: "Battery" },
		{ emoji: "🔌", name: "Electric Plug" },
		{ emoji: "💡", name: "Light Bulb" },
		{ emoji: "🔦", name: "Flashlight" },
		{ emoji: "🕯️", name: "Candle" },
		{ emoji: "🪔", name: "Diya Lamp" },
		{ emoji: "🧯", name: "Fire Extinguisher" },
		{ emoji: "🛢️", name: "Oil Drum" },
		{ emoji: "💸", name: "Money with Wings" },
		{ emoji: "💵", name: "Dollar Banknote" },
		{ emoji: "💴", name: "Yen Banknote" },
		{ emoji: "💶", name: "Euro Banknote" },
		{ emoji: "💷", name: "Pound Banknote" },
		{ emoji: "🪙", name: "Coin" },
		{ emoji: "💰", name: "Money Bag" },
		{ emoji: "💳", name: "Credit Card" },
		{ emoji: "💎", name: "Gem Stone" },
		{ emoji: "⚖️", name: "Balance Scale" },
		{ emoji: "🪜", name: "Ladder" },
		{ emoji: "🧰", name: "Toolbox" },
		{ emoji: "🪛", name: "Screwdriver" },
		{ emoji: "🪚", name: "Carpentry Saw" },
		{ emoji: "🔩", name: "Nut and Bolt" },
		{ emoji: "⚙️", name: "Gear" },
		{ emoji: "🧲", name: "Magnet" },
		{ emoji: "🧪", name: "Test Tube" },
		{ emoji: "🧫", name: "Petri Dish" },
		{ emoji: "🧬", name: "DNA" },
		{ emoji: "🔬", name: "Microscope" },
		{ emoji: "🔭", name: "Telescope" },
		{ emoji: "📡", name: "Satellite Antenna" },
	],

	time: [
		{ emoji: "🕐", name: "One Oclock" },
		{ emoji: "🕑", name: "Two Oclock" },
		{ emoji: "🕒", name: "Three Oclock" },
		{ emoji: "🕓", name: "Four Oclock" },
		{ emoji: "🕔", name: "Five Oclock" },
		{ emoji: "🕕", name: "Six Oclock" },
		{ emoji: "🕖", name: "Seven Oclock" },
		{ emoji: "🕗", name: "Eight Oclock" },
		{ emoji: "🕘", name: "Nine Oclock" },
		{ emoji: "🕙", name: "Ten Oclock" },
		{ emoji: "🕚", name: "Eleven Oclock" },
		{ emoji: "🕛", name: "Twelve Oclock" },
		{ emoji: "🕜", name: "One-Thirty" },
		{ emoji: "🕝", name: "Two-Thirty" },
		{ emoji: "🕞", name: "Three-Thirty" },
		{ emoji: "🕟", name: "Four-Thirty" },
		{ emoji: "🕠", name: "Five-Thirty" },
		{ emoji: "🕡", name: "Six-Thirty" },
		{ emoji: "🕢", name: "Seven-Thirty" },
		{ emoji: "🕣", name: "Eight-Thirty" },
		{ emoji: "🕤", name: "Nine-Thirty" },
		{ emoji: "🕥", name: "Ten-Thirty" },
		{ emoji: "🕦", name: "Eleven-Thirty" },
		{ emoji: "🕧", name: "Twelve-Thirty" },
	],

	shapes: [
		{ emoji: "🔴", name: "Red Circle" },
		{ emoji: "🟠", name: "Orange Circle" },
		{ emoji: "🟡", name: "Yellow Circle" },
		{ emoji: "🟢", name: "Green Circle" },
		{ emoji: "🔵", name: "Blue Circle" },
		{ emoji: "🟣", name: "Purple Circle" },
		{ emoji: "🟤", name: "Brown Circle" },
		{ emoji: "⚫", name: "Black Circle" },
		{ emoji: "⚪", name: "White Circle" },
		{ emoji: "🟥", name: "Red Square" },
		{ emoji: "🟧", name: "Orange Square" },
		{ emoji: "🟨", name: "Yellow Square" },
		{ emoji: "🟩", name: "Green Square" },
		{ emoji: "🟦", name: "Blue Square" },
		{ emoji: "🟪", name: "Purple Square" },
		{ emoji: "🟫", name: "Brown Square" },
		{ emoji: "⬛", name: "Black Large Square" },
		{ emoji: "⬜", name: "White Large Square" },
		{ emoji: "◼️", name: "Black Medium Square" },
		{ emoji: "◻️", name: "White Medium Square" },
		{ emoji: "◾", name: "Black Medium-Small Square" },
		{ emoji: "◽", name: "White Medium-Small Square" },
		{ emoji: "▪️", name: "Black Small Square" },
		{ emoji: "▫️", name: "White Small Square" },
		{ emoji: "🔶", name: "Large Orange Diamond" },
		{ emoji: "🔷", name: "Large Blue Diamond" },
		{ emoji: "🔸", name: "Small Orange Diamond" },
		{ emoji: "🔹", name: "Small Blue Diamond" },
		{ emoji: "🔺", name: "Red Triangle Pointed Up" },
		{ emoji: "🔻", name: "Red Triangle Pointed Down" },
		{ emoji: "💠", name: "Diamond with a Dot" },
		{ emoji: "🔘", name: "Radio Button" },
		{ emoji: "🔳", name: "White Square Button" },
		{ emoji: "🔲", name: "Black Square Button" },
	],

	moreAnimals: [
		{ emoji: "🐀", name: "Rat" },
		{ emoji: "🐁", name: "Mouse" },
		{ emoji: "🐭", name: "Mouse Face" },
		{ emoji: "🐹", name: "Hamster" },
		{ emoji: "🐰", name: "Rabbit Face" },
		{ emoji: "🐇", name: "Rabbit" },
		{ emoji: "🐿️", name: "Chipmunk" },
		{ emoji: "🦫", name: "Beaver" },
		{ emoji: "🦔", name: "Hedgehog" },
		{ emoji: "🦇", name: "Bat" },
		{ emoji: "🐻", name: "Bear" },
		{ emoji: "🐻‍❄️", name: "Polar Bear" },
		{ emoji: "🐨", name: "Koala" },
		{ emoji: "🐼", name: "Panda" },
		{ emoji: "🦥", name: "Sloth" },
		{ emoji: "🦦", name: "Otter" },
		{ emoji: "🦨", name: "Skunk" },
		{ emoji: "🦘", name: "Kangaroo" },
		{ emoji: "🦡", name: "Badger" },
		{ emoji: "🐾", name: "Paw Prints" },
		{ emoji: "🦃", name: "Turkey" },
		{ emoji: "🐓", name: "Rooster" },
		{ emoji: "🐔", name: "Chicken" },
		{ emoji: "🐣", name: "Hatching Chick" },
		{ emoji: "🐤", name: "Baby Chick" },
		{ emoji: "🐥", name: "Front-Facing Baby Chick" },
		{ emoji: "🐦", name: "Bird" },
		{ emoji: "🐧", name: "Penguin" },
		{ emoji: "🕊️", name: "Dove" },
		{ emoji: "🦅", name: "Eagle" },
		{ emoji: "🦆", name: "Duck" },
		{ emoji: "🦢", name: "Swan" },
		{ emoji: "🦉", name: "Owl" },
		{ emoji: "🦤", name: "Dodo" },
		{ emoji: "🪶", name: "Feather" },
		{ emoji: "🦩", name: "Flamingo" },
		{ emoji: "🦚", name: "Peacock" },
		{ emoji: "🦜", name: "Parrot" },
	],

	moreFood: [
		{ emoji: "🫒", name: "Olive" },
		{ emoji: "🫓", name: "Flatbread" },
		{ emoji: "🧆", name: "Falafel" },
		{ emoji: "🧇", name: "Waffle" },
		{ emoji: "🥞", name: "Pancakes" },
		{ emoji: "🧈", name: "Butter" },
		{ emoji: "🧀", name: "Cheese Wedge" },
		{ emoji: "🥖", name: "Baguette Bread" },
		{ emoji: "🥐", name: "Croissant" },
		{ emoji: "🥨", name: "Pretzel" },
		{ emoji: "🥯", name: "Bagel" },
		{ emoji: "🥓", name: "Bacon" },
		{ emoji: "🥩", name: "Cut of Meat" },
		{ emoji: "🍗", name: "Poultry Leg" },
		{ emoji: "🍖", name: "Meat on Bone" },
		{ emoji: "🦴", name: "Bone" },
		{ emoji: "🌭", name: "Hot Dog" },
		{ emoji: "🍕", name: "Pizza" },
		{ emoji: "🍔", name: "Hamburger" },
		{ emoji: "🍟", name: "French Fries" },
		{ emoji: "🥙", name: "Stuffed Flatbread" },
		{ emoji: "🌮", name: "Taco" },
		{ emoji: "🌯", name: "Burrito" },
		{ emoji: "🫔", name: "Tamale" },
		{ emoji: "🥗", name: "Green Salad" },
		{ emoji: "🥘", name: "Shallow Pan of Food" },
		{ emoji: "🫕", name: "Fondue" },
		{ emoji: "🥫", name: "Canned Food" },
		{ emoji: "🍝", name: "Spaghetti" },
		{ emoji: "🍜", name: "Steaming Bowl" },
	],

	weather: [
		{ emoji: "🌀", name: "Cyclone" },
		{ emoji: "🌪️", name: "Tornado" },
		{ emoji: "🌬️", name: "Wind Face" },
		{ emoji: "🌫️", name: "Fog" },
		{ emoji: "☁️", name: "Cloud" },
		{ emoji: "⛅", name: "Sun Behind Cloud" },
		{ emoji: "⛈️", name: "Cloud with Lightning and Rain" },
		{ emoji: "🌤️", name: "Sun Behind Small Cloud" },
		{ emoji: "🌥️", name: "Sun Behind Large Cloud" },
		{ emoji: "🌦️", name: "Sun Behind Rain Cloud" },
		{ emoji: "🌧️", name: "Cloud with Rain" },
		{ emoji: "🌨️", name: "Cloud with Snow" },
		{ emoji: "🌩️", name: "Cloud with Lightning" },
		{ emoji: "⛆", name: "Heavy Rain" },
		{ emoji: "🌁", name: "Foggy" },
	],

	extra: [
		{ emoji: "🥎", name: "Softball" },
		{ emoji: "🏉", name: "Rugby Football" },
		{ emoji: "🥅", name: "Goal Net" },
		{ emoji: "⛳", name: "Flag in Hole" },
		{ emoji: "🏏", name: "Cricket Game" },
		{ emoji: "🏑", name: "Field Hockey" },
		{ emoji: "🏒", name: "Ice Hockey" },
		{ emoji: "🥍", name: "Lacrosse" },
		{ emoji: "🏓", name: "Ping Pong" },
		{ emoji: "🏸", name: "Badminton" },
		{ emoji: "🥊", name: "Boxing Glove" },
		{ emoji: "🥋", name: "Martial Arts Uniform" },
		{ emoji: "🥌", name: "Curling Stone" },
		{ emoji: "🎣", name: "Fishing Pole" },
		{ emoji: "🎿", name: "Skis" },
		{ emoji: "🛷", name: "Sled" },
		{ emoji: "🥏", name: "Flying Disc" },
		{ emoji: "🪃", name: "Boomerang" },
		{ emoji: "🎯", name: "Direct Hit" },
		{ emoji: "🪀", name: "Yo-Yo" },
		{ emoji: "🪁", name: "Kite" },
		{ emoji: "🎳", name: "Bowling" },
		{ emoji: "♟️", name: "Chess Pawn" },
		{ emoji: "🎯", name: "Bullseye" },
		{ emoji: "🎲", name: "Game Die" },
		{ emoji: "🃏", name: "Joker Card" },
		{ emoji: "🀄", name: "Mahjong Tile" },
		{ emoji: "🎴", name: "Flower Cards" },
		{ emoji: "🎰", name: "Slot Machine" },
		{ emoji: "🧩", name: "Jigsaw Piece" },
		{ emoji: "🪆", name: "Russian Dolls" },
		{ emoji: "🧸", name: "Teddy" },
		{ emoji: "🪅", name: "Party Pinata" },
		{ emoji: "🎊", name: "Confetti" },
		{ emoji: "🎉", name: "Party" },
		{ emoji: "🎈", name: "Red Balloon" },
		{ emoji: "🎏", name: "Carp Banner" },
		{ emoji: "🎐", name: "Wind Bell" },
		{ emoji: "🧧", name: "Red Gift Envelope" },
		{ emoji: "🔖", name: "Bookmark Tab" },
		{ emoji: "🏷️", name: "Price Tag" },
		{ emoji: "📛", name: "Badge" },
		{ emoji: "🪬", name: "Hand Amulet" },
		{ emoji: "🧿", name: "Eye Bead" },
		{ emoji: "🪄", name: "Wand" },
	],
};

// Flatten and shuffle categories to avoid consecutive similar emojis
function generateCalendar() {
	const calendar = [];
	const categoryKeys = Object.keys(emojiCategories);

	// Flatten all emojis from all categories
	const allEmojis = [];
	for (const key of categoryKeys) {
		allEmojis.push(...emojiCategories[key]);
	}

	// Remove duplicates by emoji
	const seen = new Set();
	const uniqueEmojis = allEmojis.filter((item) => {
		if (seen.has(item.emoji)) {
			return false;
		}
		seen.add(item.emoji);
		return true;
	});

	// Helper: Check similarity between two emoji names
	function getSimilarityScore(name1, name2) {
		const words1 = name1.toLowerCase().split(/\s+/);
		const words2 = name2.toLowerCase().split(/\s+/);

		// Count common words
		let commonWords = 0;
		for (const word of words1) {
			if (words2.includes(word)) {
				commonWords++;
			}
		}

		// Higher score = more similar
		return commonWords;
	}

	// Greedy algorithm: pick emojis that are least similar to recent ones
	const result = [];
	const remaining = [...uniqueEmojis];
	const lookBackWindow = 15; // Check last 15 emojis for similarity

	//  Start with a random emoji
	const firstIndex = Math.floor(Math.random() * remaining.length);
	result.push(remaining[firstIndex]);
	remaining.splice(firstIndex, 1);

	while (remaining.length > 0) {
		let bestIndex = 0;
		let lowestSimilarity = Infinity;

		// Find emoji with lowest similarity to recent ones
		for (let i = 0; i < remaining.length; i++) {
			const candidate = remaining[i];

			// Calculate total similarity to last N emojis
			let totalSimilarity = 0;
			const recentCount = Math.min(lookBackWindow, result.length);

			for (let j = 0; j < recentCount; j++) {
				const recent = result[result.length - 1 - j];
				const weight = 1 / (j + 1); // More recent = higher weight
				totalSimilarity +=
					getSimilarityScore(candidate.name, recent.name) * weight;
			}

			if (totalSimilarity < lowestSimilarity) {
				lowestSimilarity = totalSimilarity;
				bestIndex = i;
			}
		}

		result.push(remaining[bestIndex]);
		remaining.splice(bestIndex, 1);
	}

	console.log(`Generated ${result.length} unique emojis`);
	console.log(`Target: 1096 emojis (3 years including 1 leap year)`);

	if (result.length >= 1096) {
		console.log(`✓ Sufficient emojis for 3 years!`);
		return result.slice(0, 1096); // Take exactly 1096
	} else {
		// If we're close but not quite there, repeat some popular/fun emojis at the end
		const popularEmojis = [
			{ emoji: "✨", name: "Sparkles" },
			{ emoji: "🌟", name: "Glowing Star" },
			{ emoji: "🎉", name: "Party Popper" },
			{ emoji: "🎊", name: "Confetti Ball" },
			{ emoji: "🎈", name: "Balloon" },
			{ emoji: "🔥", name: "Fire" },
			{ emoji: "💫", name: "Dizzy" },
			{ emoji: "🌈", name: "Rainbow" },
			{ emoji: "⭐", name: "Star" },
			{ emoji: "💎", name: "Gem" },
			{ emoji: "🏆", name: "Trophy" },
			{ emoji: "🎯", name: "Bullseye" },
			{ emoji: "🎨", name: "Art Palette" },
			{ emoji: "🎭", name: "Theater" },
			{ emoji: "🎪", name: "Circus" },
			{ emoji: "🎬", name: "Movie Clapper" },
			{ emoji: "🎮", name: "Video Game" },
			{ emoji: "🧩", name: "Puzzle" },
			{ emoji: "🎲", name: "Dice" },
			{ emoji: "🎰", name: "Slots" },
			{ emoji: "🎳", name: "Bowling" },
			{ emoji: "🥇", name: "Gold Medal" },
			{ emoji: "🥈", name: "Silver Medal" },
			{ emoji: "🥉", name: "Bronze Medal" },
			{ emoji: "🏅", name: "Medal" },
			{ emoji: "🎖️", name: "Military Medal" },
			{ emoji: "🔮", name: "Crystal Ball" },
			{ emoji: "🪄", name: "Magic Wand" },
			{ emoji: "🌺", name: "Hibiscus" },
			{ emoji: "🌸", name: "Cherry Blossom" },
			{ emoji: "🌼", name: "Blossom" },
			{ emoji: "🌻", name: "Sunflower" },
			{ emoji: "🌷", name: "Tulip" },
			{ emoji: "🌹", name: "Rose" },
			{ emoji: "💐", name: "Bouquet" },
			{ emoji: "🦄", name: "Unicorn" },
			{ emoji: "🐉", name: "Dragon" },
		];

		// Add popular emojis to fill the gap
		let index = 0;
		while (result.length < 1096) {
			const item = popularEmojis[index % popularEmojis.length];
			result.push({
				emoji: item.emoji,
				name: `${item.name} (${Math.floor(index / popularEmojis.length) + 2})`,
			});
			index++;
		}

		console.log(
			`✓ Reached 1096 with ${uniqueEmojis.length} unique + ${result.length - uniqueEmojis.length} curated repeats!`,
		);
		return result;
	}
}

// Generate and save
const calendar = generateCalendar();
const outputPath = join(__dirname, "../data/emoji_calendar.json");
writeFileSync(outputPath, JSON.stringify(calendar, null, "\t"));

console.log(`\n✅ Emoji calendar saved to ${outputPath}`);
console.log(`\nBreakdown by year:`);
console.log(`- Year 1 (365 days): Days 1-365`);
console.log(`- Year 2 (365 days): Days 366-730`);
console.log(`- Year 3 (366 days, leap year): Days 731-1096`);
console.log(`\nTotal unique emojis: ${calendar.length}`);
