import { writeFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Comprehensive emoji categories (excluding trophy 🏆 and slide 🛝 as they're in the UI)
const emojiCategories = {
	// Smileys & Emotion
	emotions: [
		{ emoji: "😀", name: "Grinning Face" },
		{ emoji: "😃", name: "Grinning Face with Big Eyes" },
		{ emoji: "😄", name: "Grinning Face with Smiling Eyes" },
		{ emoji: "😁", name: "Beaming Face with Smiling Eyes" },
		{ emoji: "😆", name: "Grinning Squinting Face" },
		{ emoji: "😅", name: "Grinning Face with Sweat" },
		{ emoji: "🤣", name: "Rolling on the Floor Laughing" },
		{ emoji: "😂", name: "Face with Tears of Joy" },
		{ emoji: "🙂", name: "Slightly Smiling Face" },
		{ emoji: "🙃", name: "Upside-Down Face" },
		{ emoji: "😉", name: "Winking Face" },
		{ emoji: "😊", name: "Smiling Face with Smiling Eyes" },
		{ emoji: "😇", name: "Smiling Face with Halo" },
		{ emoji: "🥰", name: "Smiling Face with Hearts" },
		{ emoji: "😍", name: "Smiling Face with Heart-Eyes" },
		{ emoji: "🤩", name: "Star-Struck" },
		{ emoji: "😘", name: "Face Blowing a Kiss" },
		{ emoji: "😗", name: "Kissing Face" },
		{ emoji: "😚", name: "Kissing Face with Closed Eyes" },
		{ emoji: "😙", name: "Kissing Face with Smiling Eyes" },
		{ emoji: "😋", name: "Face Savoring Food" },
		{ emoji: "😛", name: "Face with Tongue" },
		{ emoji: "😜", name: "Winking Face with Tongue" },
		{ emoji: "🤪", name: "Zany Face" },
		{ emoji: "😝", name: "Squinting Face with Tongue" },
		{ emoji: "🤑", name: "Money-Mouth Face" },
		{ emoji: "🤗", name: "Hugging Face" },
		{ emoji: "🤭", name: "Face with Hand Over Mouth" },
		{ emoji: "🤫", name: "Shushing Face" },
		{ emoji: "🤔", name: "Thinking Face" },
		{ emoji: "🤐", name: "Zipper-Mouth Face" },
		{ emoji: "🤨", name: "Face with Raised Eyebrow" },
		{ emoji: "😐", name: "Neutral Face" },
		{ emoji: "😑", name: "Expressionless Face" },
		{ emoji: "😶", name: "Face Without Mouth" },
		{ emoji: "😏", name: "Smirking Face" },
		{ emoji: "😒", name: "Unamused Face" },
		{ emoji: "🙄", name: "Face with Rolling Eyes" },
		{ emoji: "😬", name: "Grimacing Face" },
		{ emoji: "🤥", name: "Lying Face" },
		{ emoji: "😌", name: "Relieved Face" },
		{ emoji: "😔", name: "Pensive Face" },
		{ emoji: "😪", name: "Sleepy Face" },
		{ emoji: "🤤", name: "Drooling Face" },
		{ emoji: "😴", name: "Sleeping Face" },
		{ emoji: "😷", name: "Face with Medical Mask" },
		{ emoji: "🤒", name: "Face with Thermometer" },
		{ emoji: "🤕", name: "Face with Head-Bandage" },
		{ emoji: "🤢", name: "Nauseated Face" },
		{ emoji: "🤮", name: "Face Vomiting" },
		{ emoji: "🤧", name: "Sneezing Face" },
		{ emoji: "🥵", name: "Hot Face" },
		{ emoji: "🥶", name: "Cold Face" },
		{ emoji: "😵", name: "Dizzy Face" },
		{ emoji: "🤯", name: "Exploding Head" },
		{ emoji: "🤠", name: "Cowboy Hat Face" },
		{ emoji: "🥳", name: "Partying Face" },
		{ emoji: "😎", name: "Smiling Face with Sunglasses" },
		{ emoji: "🤓", name: "Nerd Face" },
		{ emoji: "🧐", name: "Face with Monocle" },
		{ emoji: "😕", name: "Confused Face" },
		{ emoji: "😟", name: "Worried Face" },
		{ emoji: "🙁", name: "Slightly Frowning Face" },
		{ emoji: "☹️", name: "Frowning Face" },
		{ emoji: "😮", name: "Face with Open Mouth" },
		{ emoji: "😯", name: "Hushed Face" },
		{ emoji: "😲", name: "Astonished Face" },
		{ emoji: "😳", name: "Flushed Face" },
		{ emoji: "🥺", name: "Pleading Face" },
		{ emoji: "😦", name: "Frowning Face with Open Mouth" },
		{ emoji: "😧", name: "Anguished Face" },
		{ emoji: "😨", name: "Fearful Face" },
		{ emoji: "😰", name: "Anxious Face with Sweat" },
		{ emoji: "😥", name: "Sad but Relieved Face" },
		{ emoji: "😢", name: "Crying Face" },
		{ emoji: "😭", name: "Loudly Crying Face" },
		{ emoji: "😱", name: "Face Screaming in Fear" },
		{ emoji: "😖", name: "Confounded Face" },
		{ emoji: "😣", name: "Persevering Face" },
		{ emoji: "😞", name: "Disappointed Face" },
		{ emoji: "😓", name: "Downcast Face with Sweat" },
		{ emoji: "😩", name: "Weary Face" },
		{ emoji: "😫", name: "Tired Face" },
		{ emoji: "🥱", name: "Yawning Face" },
		{ emoji: "😤", name: "Face with Steam From Nose" },
		{ emoji: "😡", name: "Pouting Face" },
		{ emoji: "😠", name: "Angry Face" },
		{ emoji: "🤬", name: "Face with Symbols on Mouth" },
		{ emoji: "😈", name: "Smiling Face with Horns" },
		{ emoji: "👿", name: "Angry Face with Horns" },
		{ emoji: "💀", name: "Skull" },
		{ emoji: "☠️", name: "Skull and Crossbones" },
		{ emoji: "💩", name: "Pile of Poo" },
		{ emoji: "🤡", name: "Clown Face" },
		{ emoji: "👹", name: "Ogre" },
		{ emoji: "👺", name: "Goblin" },
		{ emoji: "👻", name: "Ghost" },
		{ emoji: "👽", name: "Alien" },
		{ emoji: "👾", name: "Alien Monster" },
		{ emoji: "🤖", name: "Robot" },
	],

	// Animals & Nature
	animals: [
		{ emoji: "🐵", name: "Monkey Face" },
		{ emoji: "🐒", name: "Monkey" },
		{ emoji: "🦍", name: "Gorilla" },
		{ emoji: "🦧", name: "Orangutan" },
		{ emoji: "🐶", name: "Dog Face" },
		{ emoji: "🐕", name: "Dog" },
		{ emoji: "🦮", name: "Guide Dog" },
		{ emoji: "🐩", name: "Poodle" },
		{ emoji: "🐺", name: "Wolf" },
		{ emoji: "🦊", name: "Fox" },
		{ emoji: "🦝", name: "Raccoon" },
		{ emoji: "🐱", name: "Cat Face" },
		{ emoji: "🐈", name: "Cat" },
		{ emoji: "🦁", name: "Lion" },
		{ emoji: "🐯", name: "Tiger Face" },
		{ emoji: "🐅", name: "Tiger" },
		{ emoji: "🐆", name: "Leopard" },
		{ emoji: "🐴", name: "Horse Face" },
		{ emoji: "🐎", name: "Horse" },
		{ emoji: "🦄", name: "Unicorn" },
		{ emoji: "🦓", name: "Zebra" },
		{ emoji: "🦌", name: "Deer" },
		{ emoji: "🐮", name: "Cow Face" },
		{ emoji: "🐂", name: "Ox" },
		{ emoji: "🐃", name: "Water Buffalo" },
		{ emoji: "🐄", name: "Cow" },
		{ emoji: "🐷", name: "Pig Face" },
		{ emoji: "🐖", name: "Pig" },
		{ emoji: "🐗", name: "Boar" },
		{ emoji: "🐽", name: "Pig Nose" },
		{ emoji: "🐏", name: "Ram" },
		{ emoji: "🐑", name: "Ewe" },
		{ emoji: "🐐", name: "Goat" },
		{ emoji: "🐪", name: "Camel" },
		{ emoji: "🐫", name: "Two-Hump Camel" },
		{ emoji: "🦙", name: "Llama" },
		{ emoji: "🦒", name: "Giraffe" },
		{ emoji: "🐘", name: "Elephant" },
		{ emoji: "🦏", name: "Rhinoceros" },
		{ emoji: "🦛", name: "Hippopotamus" },
		{ emoji: "🐭", name: "Mouse Face" },
		{ emoji: "🐁", name: "Mouse" },
		{ emoji: "🐀", name: "Rat" },
		{ emoji: "🐹", name: "Hamster" },
		{ emoji: "🐰", name: "Rabbit Face" },
		{ emoji: "🐇", name: "Rabbit" },
		{ emoji: "🐿️", name: "Chipmunk" },
		{ emoji: "🦔", name: "Hedgehog" },
		{ emoji: "🦇", name: "Bat" },
		{ emoji: "🐻", name: "Bear" },
		{ emoji: "🐨", name: "Koala" },
		{ emoji: "🐼", name: "Panda" },
		{ emoji: "🦥", name: "Sloth" },
		{ emoji: "🦦", name: "Otter" },
		{ emoji: "🦨", name: "Skunk" },
		{ emoji: "🦘", name: "Kangaroo" },
		{ emoji: "🦡", name: "Badger" },
		{ emoji: "🐾", name: "Paw Prints" },
		{ emoji: "🦃", name: "Turkey" },
		{ emoji: "🐔", name: "Chicken" },
		{ emoji: "🐓", name: "Rooster" },
		{ emoji: "🐣", name: "Hatching Chick" },
		{ emoji: "🐤", name: "Baby Chick" },
		{ emoji: "🐥", name: "Front-Facing Baby Chick" },
		{ emoji: "🐦", name: "Bird" },
		{ emoji: "🐧", name: "Penguin" },
		{ emoji: "🕊️", name: "Dove" },
		{ emoji: "🦅", name: "Eagle" },
		{ emoji: "🦆", name: "Duck" },
		{ emoji: "🦢", name: "Swan" },
		{ emoji: "🦉", name: "Owl" },
		{ emoji: "🦩", name: "Flamingo" },
		{ emoji: "🦚", name: "Peacock" },
		{ emoji: "🦜", name: "Parrot" },
		{ emoji: "🐸", name: "Frog" },
		{ emoji: "🐊", name: "Crocodile" },
		{ emoji: "🐢", name: "Turtle" },
		{ emoji: "🦎", name: "Lizard" },
		{ emoji: "🐍", name: "Snake" },
		{ emoji: "🐲", name: "Dragon Face" },
		{ emoji: "🐉", name: "Dragon" },
		{ emoji: "🦕", name: "Sauropod" },
		{ emoji: "🦖", name: "T-Rex" },
		{ emoji: "🐳", name: "Spouting Whale" },
		{ emoji: "🐋", name: "Whale" },
		{ emoji: "🐬", name: "Dolphin" },
		{ emoji: "🐟", name: "Fish" },
		{ emoji: "🐠", name: "Tropical Fish" },
		{ emoji: "🐡", name: "Blowfish" },
		{ emoji: "🦈", name: "Shark" },
		{ emoji: "🐙", name: "Octopus" },
		{ emoji: "🐚", name: "Spiral Shell" },
		{ emoji: "🐌", name: "Snail" },
		{ emoji: "🦋", name: "Butterfly" },
		{ emoji: "🐛", name: "Bug" },
		{ emoji: "🐜", name: "Ant" },
		{ emoji: "🐝", name: "Honeybee" },
		{ emoji: "🐞", name: "Lady Beetle" },
		{ emoji: "🦗", name: "Cricket" },
		{ emoji: "🕷️", name: "Spider" },
		{ emoji: "🕸️", name: "Spider Web" },
		{ emoji: "🦂", name: "Scorpion" },
		{ emoji: "🦟", name: "Mosquito" },
		{ emoji: "🦠", name: "Microbe" },
	],

	// Food & Drink
	food: [
		{ emoji: "🍇", name: "Grapes" },
		{ emoji: "🍈", name: "Melon" },
		{ emoji: "🍉", name: "Watermelon" },
		{ emoji: "🍊", name: "Tangerine" },
		{ emoji: "🍋", name: "Lemon" },
		{ emoji: "🍌", name: "Banana" },
		{ emoji: "🍍", name: "Pineapple" },
		{ emoji: "🥭", name: "Mango" },
		{ emoji: "🍎", name: "Red Apple" },
		{ emoji: "🍏", name: "Green Apple" },
		{ emoji: "🍐", name: "Pear" },
		{ emoji: "🍑", name: "Peach" },
		{ emoji: "🍒", name: "Cherries" },
		{ emoji: "🍓", name: "Strawberry" },
		{ emoji: "🥝", name: "Kiwi Fruit" },
		{ emoji: "🍅", name: "Tomato" },
		{ emoji: "🥥", name: "Coconut" },
		{ emoji: "🥑", name: "Avocado" },
		{ emoji: "🍆", name: "Eggplant" },
		{ emoji: "🥔", name: "Potato" },
		{ emoji: "🥕", name: "Carrot" },
		{ emoji: "🌽", name: "Ear of Corn" },
		{ emoji: "🌶️", name: "Hot Pepper" },
		{ emoji: "🥒", name: "Cucumber" },
		{ emoji: "🥬", name: "Leafy Green" },
		{ emoji: "🥦", name: "Broccoli" },
		{ emoji: "🧄", name: "Garlic" },
		{ emoji: "🧅", name: "Onion" },
		{ emoji: "🍄", name: "Mushroom" },
		{ emoji: "🥜", name: "Peanuts" },
		{ emoji: "🌰", name: "Chestnut" },
		{ emoji: "🍞", name: "Bread" },
		{ emoji: "🥐", name: "Croissant" },
		{ emoji: "🥖", name: "Baguette Bread" },
		{ emoji: "🥨", name: "Pretzel" },
		{ emoji: "🥯", name: "Bagel" },
		{ emoji: "🥞", name: "Pancakes" },
		{ emoji: "🧇", name: "Waffle" },
		{ emoji: "🧀", name: "Cheese Wedge" },
		{ emoji: "🍖", name: "Meat on Bone" },
		{ emoji: "🍗", name: "Poultry Leg" },
		{ emoji: "🥩", name: "Cut of Meat" },
		{ emoji: "🥓", name: "Bacon" },
		{ emoji: "🍔", name: "Hamburger" },
		{ emoji: "🍟", name: "French Fries" },
		{ emoji: "🍕", name: "Pizza" },
		{ emoji: "🌭", name: "Hot Dog" },
		{ emoji: "🥪", name: "Sandwich" },
		{ emoji: "🌮", name: "Taco" },
		{ emoji: "🌯", name: "Burrito" },
		{ emoji: "🥙", name: "Stuffed Flatbread" },
		{ emoji: "🧆", name: "Falafel" },
		{ emoji: "🥚", name: "Egg" },
		{ emoji: "🍳", name: "Cooking" },
		{ emoji: "🥘", name: "Shallow Pan of Food" },
		{ emoji: "🍲", name: "Pot of Food" },
		{ emoji: "🥣", name: "Bowl with Spoon" },
		{ emoji: "🥗", name: "Green Salad" },
		{ emoji: "🍿", name: "Popcorn" },
		{ emoji: "🧈", name: "Butter" },
		{ emoji: "🧂", name: "Salt" },
		{ emoji: "🥫", name: "Canned Food" },
		{ emoji: "🍱", name: "Bento Box" },
		{ emoji: "🍘", name: "Rice Cracker" },
		{ emoji: "🍙", name: "Rice Ball" },
		{ emoji: "🍚", name: "Cooked Rice" },
		{ emoji: "🍛", name: "Curry Rice" },
		{ emoji: "🍜", name: "Steaming Bowl" },
		{ emoji: "🍝", name: "Spaghetti" },
		{ emoji: "🍠", name: "Roasted Sweet Potato" },
		{ emoji: "🍢", name: "Oden" },
		{ emoji: "🍣", name: "Sushi" },
		{ emoji: "🍤", name: "Fried Shrimp" },
		{ emoji: "🍥", name: "Fish Cake with Swirl" },
		{ emoji: "🥮", name: "Moon Cake" },
		{ emoji: "🍡", name: "Dango" },
		{ emoji: "🥟", name: "Dumpling" },
		{ emoji: "🥠", name: "Fortune Cookie" },
		{ emoji: "🥡", name: "Takeout Box" },
		{ emoji: "🦀", name: "Crab" },
		{ emoji: "🦞", name: "Lobster" },
		{ emoji: "🦐", name: "Shrimp" },
		{ emoji: "🦑", name: "Squid" },
		{ emoji: "🦪", name: "Oyster" },
		{ emoji: "🍦", name: "Soft Ice Cream" },
		{ emoji: "🍧", name: "Shaved Ice" },
		{ emoji: "🍨", name: "Ice Cream" },
		{ emoji: "🍩", name: "Doughnut" },
		{ emoji: "🍪", name: "Cookie" },
		{ emoji: "🎂", name: "Birthday Cake" },
		{ emoji: "🍰", name: "Shortcake" },
		{ emoji: "🧁", name: "Cupcake" },
		{ emoji: "🥧", name: "Pie" },
		{ emoji: "🍫", name: "Chocolate Bar" },
		{ emoji: "🍬", name: "Candy" },
		{ emoji: "🍭", name: "Lollipop" },
		{ emoji: "🍮", name: "Custard" },
		{ emoji: "🍯", name: "Honey Pot" },
		{ emoji: "🍼", name: "Baby Bottle" },
		{ emoji: "🥛", name: "Glass of Milk" },
		{ emoji: "☕", name: "Hot Beverage" },
		{ emoji: "🍵", name: "Teacup Without Handle" },
		{ emoji: "🍶", name: "Sake" },
		{ emoji: "🍾", name: "Bottle with Popping Cork" },
		{ emoji: "🍷", name: "Wine Glass" },
		{ emoji: "🍸", name: "Cocktail Glass" },
		{ emoji: "🍹", name: "Tropical Drink" },
		{ emoji: "🍺", name: "Beer Mug" },
		{ emoji: "🍻", name: "Clinking Beer Mugs" },
		{ emoji: "🥂", name: "Clinking Glasses" },
		{ emoji: "🥃", name: "Tumbler Glass" },
		{ emoji: "🥤", name: "Cup with Straw" },
		{ emoji: "🧃", name: "Beverage Box" },
		{ emoji: "🧉", name: "Mate" },
		{ emoji: "🧊", name: "Ice" },
	],

	// Activities & Sports
	activities: [
		{ emoji: "⚽", name: "Soccer Ball" },
		{ emoji: "🏀", name: "Basketball" },
		{ emoji: "🏈", name: "American Football" },
		{ emoji: "⚾", name: "Baseball" },
		{ emoji: "🥎", name: "Softball" },
		{ emoji: "🎾", name: "Tennis" },
		{ emoji: "🏐", name: "Volleyball" },
		{ emoji: "🏉", name: "Rugby Football" },
		{ emoji: "🥏", name: "Flying Disc" },
		{ emoji: "🎱", name: "Pool 8 Ball" },
		{ emoji: "🏓", name: "Ping Pong" },
		{ emoji: "🏸", name: "Badminton" },
		{ emoji: "🏒", name: "Ice Hockey" },
		{ emoji: "🏑", name: "Field Hockey" },
		{ emoji: "🥍", name: "Lacrosse" },
		{ emoji: "🏏", name: "Cricket Game" },
		{ emoji: "🥅", name: "Goal Net" },
		{ emoji: "⛳", name: "Flag in Hole" },
		{ emoji: "🏹", name: "Bow and Arrow" },
		{ emoji: "🎣", name: "Fishing Pole" },
		{ emoji: "🤿", name: "Diving Mask" },
		{ emoji: "🥊", name: "Boxing Glove" },
		{ emoji: "🥋", name: "Martial Arts Uniform" },
		{ emoji: "🎽", name: "Running Shirt" },
		{ emoji: "🛹", name: "Skateboard" },
		{ emoji: "⛸️", name: "Ice Skate" },
		{ emoji: "🥌", name: "Curling Stone" },
		{ emoji: "🎿", name: "Skis" },
		{ emoji: "⛷️", name: "Skier" },
		{ emoji: "🏂", name: "Snowboarder" },
		{ emoji: "🏋️", name: "Person Lifting Weights" },
		{ emoji: "🤺", name: "Person Fencing" },
		{ emoji: "🤼", name: "People Wrestling" },
		{ emoji: "🤸", name: "Person Cartwheeling" },
		{ emoji: "🤾", name: "Person Playing Handball" },
		{ emoji: "🤽", name: "Person Playing Water Polo" },
		{ emoji: "🎪", name: "Circus Tent" },
		{ emoji: "🎭", name: "Performing Arts" },
		{ emoji: "🎨", name: "Artist Palette" },
		{ emoji: "🎬", name: "Clapper Board" },
		{ emoji: "🎤", name: "Microphone" },
		{ emoji: "🎧", name: "Headphone" },
		{ emoji: "🎼", name: "Musical Score" },
		{ emoji: "🎹", name: "Musical Keyboard" },
		{ emoji: "🥁", name: "Drum" },
		{ emoji: "🎷", name: "Saxophone" },
		{ emoji: "🎺", name: "Trumpet" },
		{ emoji: "🎸", name: "Guitar" },
		{ emoji: "🎻", name: "Violin" },
		{ emoji: "🎲", name: "Game Die" },
		{ emoji: "🎯", name: "Direct Hit" },
		{ emoji: "🎳", name: "Bowling" },
		{ emoji: "🎮", name: "Video Game" },
		{ emoji: "🎰", name: "Slot Machine" },
		{ emoji: "🧩", name: "Puzzle Piece" },
	],

	// Travel & Places
	places: [
		{ emoji: "🚗", name: "Automobile" },
		{ emoji: "🚕", name: "Taxi" },
		{ emoji: "🚙", name: "Sport Utility Vehicle" },
		{ emoji: "🚌", name: "Bus" },
		{ emoji: "🚎", name: "Trolleybus" },
		{ emoji: "🏎️", name: "Racing Car" },
		{ emoji: "🚓", name: "Police Car" },
		{ emoji: "🚑", name: "Ambulance" },
		{ emoji: "🚒", name: "Fire Engine" },
		{ emoji: "🚐", name: "Minibus" },
		{ emoji: "🚚", name: "Delivery Truck" },
		{ emoji: "🚛", name: "Articulated Lorry" },
		{ emoji: "🚜", name: "Tractor" },
		{ emoji: "🦯", name: "White Cane" },
		{ emoji: "🦽", name: "Manual Wheelchair" },
		{ emoji: "🦼", name: "Motorized Wheelchair" },
		{ emoji: "🛴", name: "Kick Scooter" },
		{ emoji: "🚲", name: "Bicycle" },
		{ emoji: "🛵", name: "Motor Scooter" },
		{ emoji: "🏍️", name: "Motorcycle" },
		{ emoji: "🛺", name: "Auto Rickshaw" },
		{ emoji: "🚨", name: "Police Car Light" },
		{ emoji: "🚔", name: "Oncoming Police Car" },
		{ emoji: "🚍", name: "Oncoming Bus" },
		{ emoji: "🚘", name: "Oncoming Automobile" },
		{ emoji: "🚖", name: "Oncoming Taxi" },
		{ emoji: "🚡", name: "Aerial Tramway" },
		{ emoji: "🚠", name: "Mountain Cableway" },
		{ emoji: "🚟", name: "Suspension Railway" },
		{ emoji: "🚃", name: "Railway Car" },
		{ emoji: "🚋", name: "Tram Car" },
		{ emoji: "🚞", name: "Mountain Railway" },
		{ emoji: "🚝", name: "Monorail" },
		{ emoji: "🚄", name: "High-Speed Train" },
		{ emoji: "🚅", name: "Bullet Train" },
		{ emoji: "🚈", name: "Light Rail" },
		{ emoji: "🚂", name: "Locomotive" },
		{ emoji: "🚆", name: "Train" },
		{ emoji: "🚇", name: "Metro" },
		{ emoji: "🚊", name: "Tram" },
		{ emoji: "🚉", name: "Station" },
		{ emoji: "✈️", name: "Airplane" },
		{ emoji: "🛫", name: "Airplane Departure" },
		{ emoji: "🛬", name: "Airplane Arrival" },
		{ emoji: "🛩️", name: "Small Airplane" },
		{ emoji: "💺", name: "Seat" },
		{ emoji: "🛰️", name: "Satellite" },
		{ emoji: "🚁", name: "Helicopter" },
		{ emoji: "🛶", name: "Canoe" },
		{ emoji: "⛵", name: "Sailboat" },
		{ emoji: "🚤", name: "Speedboat" },
		{ emoji: "🛥️", name: "Motor Boat" },
		{ emoji: "🛳️", name: "Passenger Ship" },
		{ emoji: "⛴️", name: "Ferry" },
		{ emoji: "🚢", name: "Ship" },
		{ emoji: "⚓", name: "Anchor" },
		{ emoji: "⛽", name: "Fuel Pump" },
		{ emoji: "🚧", name: "Construction" },
		{ emoji: "🚦", name: "Vertical Traffic Light" },
		{ emoji: "🚥", name: "Horizontal Traffic Light" },
		{ emoji: "🗺️", name: "World Map" },
		{ emoji: "🗿", name: "Moai" },
		{ emoji: "🗽", name: "Statue of Liberty" },
		{ emoji: "🗼", name: "Tokyo Tower" },
		{ emoji: "🏰", name: "Castle" },
		{ emoji: "🏯", name: "Japanese Castle" },
		{ emoji: "🏟️", name: "Stadium" },
		{ emoji: "🎡", name: "Ferris Wheel" },
		{ emoji: "🎢", name: "Roller Coaster" },
		{ emoji: "🎠", name: "Carousel Horse" },
		{ emoji: "⛲", name: "Fountain" },
		{ emoji: "⛱️", name: "Umbrella on Ground" },
		{ emoji: "🏖️", name: "Beach with Umbrella" },
		{ emoji: "🏝️", name: "Desert Island" },
		{ emoji: "🏜️", name: "Desert" },
		{ emoji: "🌋", name: "Volcano" },
		{ emoji: "⛰️", name: "Mountain" },
		{ emoji: "🏔️", name: "Snow-Capped Mountain" },
		{ emoji: "🗻", name: "Mount Fuji" },
		{ emoji: "🏕️", name: "Camping" },
		{ emoji: "⛺", name: "Tent" },
		{ emoji: "🏠", name: "House" },
		{ emoji: "🏡", name: "House with Garden" },
		{ emoji: "🏘️", name: "Houses" },
		{ emoji: "🏚️", name: "Derelict House" },
		{ emoji: "🏗️", name: "Building Construction" },
		{ emoji: "🏭", name: "Factory" },
		{ emoji: "🏢", name: "Office Building" },
		{ emoji: "🏬", name: "Department Store" },
		{ emoji: "🏣", name: "Japanese Post Office" },
		{ emoji: "🏤", name: "Post Office" },
		{ emoji: "🏥", name: "Hospital" },
		{ emoji: "🏦", name: "Bank" },
		{ emoji: "🏨", name: "Hotel" },
		{ emoji: "🏪", name: "Convenience Store" },
		{ emoji: "🏫", name: "School" },
		{ emoji: "🏩", name: "Love Hotel" },
		{ emoji: "💒", name: "Wedding" },
		{ emoji: "🏛️", name: "Classical Building" },
		{ emoji: "⛪", name: "Church" },
		{ emoji: "🕌", name: "Mosque" },
		{ emoji: "🕍", name: "Synagogue" },
		{ emoji: "⛩️", name: "Shinto Shrine" },
		{ emoji: "🕋", name: "Kaaba" },
	],

	// Objects
	objects: [
		{ emoji: "⌚", name: "Watch" },
		{ emoji: "📱", name: "Mobile Phone" },
		{ emoji: "📲", name: "Mobile Phone with Arrow" },
		{ emoji: "💻", name: "Laptop" },
		{ emoji: "⌨️", name: "Keyboard" },
		{ emoji: "🖥️", name: "Desktop Computer" },
		{ emoji: "🖨️", name: "Printer" },
		{ emoji: "🖱️", name: "Computer Mouse" },
		{ emoji: "🖲️", name: "Trackball" },
		{ emoji: "🕹️", name: "Joystick" },
		{ emoji: "🗜️", name: "Clamp" },
		{ emoji: "💽", name: "Computer Disk" },
		{ emoji: "💾", name: "Floppy Disk" },
		{ emoji: "💿", name: "Optical Disk" },
		{ emoji: "📀", name: "DVD" },
		{ emoji: "📼", name: "Videocassette" },
		{ emoji: "📷", name: "Camera" },
		{ emoji: "📸", name: "Camera with Flash" },
		{ emoji: "📹", name: "Video Camera" },
		{ emoji: "🎥", name: "Movie Camera" },
		{ emoji: "📽️", name: "Film Projector" },
		{ emoji: "🎞️", name: "Film Frames" },
		{ emoji: "📞", name: "Telephone Receiver" },
		{ emoji: "☎️", name: "Telephone" },
		{ emoji: "📟", name: "Pager" },
		{ emoji: "📠", name: "Fax Machine" },
		{ emoji: "📺", name: "Television" },
		{ emoji: "📻", name: "Radio" },
		{ emoji: "🎙️", name: "Studio Microphone" },
		{ emoji: "🎚️", name: "Level Slider" },
		{ emoji: "🎛️", name: "Control Knobs" },
		{ emoji: "🧭", name: "Compass" },
		{ emoji: "⏱️", name: "Stopwatch" },
		{ emoji: "⏲️", name: "Timer Clock" },
		{ emoji: "⏰", name: "Alarm Clock" },
		{ emoji: "🕰️", name: "Mantelpiece Clock" },
		{ emoji: "⌛", name: "Hourglass Done" },
		{ emoji: "⏳", name: "Hourglass Not Done" },
		{ emoji: "📡", name: "Satellite Antenna" },
		{ emoji: "🔋", name: "Battery" },
		{ emoji: "🔌", name: "Electric Plug" },
		{ emoji: "💡", name: "Light Bulb" },
		{ emoji: "🔦", name: "Flashlight" },
		{ emoji: "🕯️", name: "Candle" },
		{ emoji: "🧯", name: "Fire Extinguisher" },
		{ emoji: "🛢️", name: "Oil Drum" },
		{ emoji: "💸", name: "Money with Wings" },
		{ emoji: "💵", name: "Dollar Banknote" },
		{ emoji: "💴", name: "Yen Banknote" },
		{ emoji: "💶", name: "Euro Banknote" },
		{ emoji: "💷", name: "Pound Banknote" },
		{ emoji: "💰", name: "Money Bag" },
		{ emoji: "💳", name: "Credit Card" },
		{ emoji: "💎", name: "Gem Stone" },
		{ emoji: "⚖️", name: "Balance Scale" },
		{ emoji: "🧰", name: "Toolbox" },
		{ emoji: "🔧", name: "Wrench" },
		{ emoji: "🔨", name: "Hammer" },
		{ emoji: "⚒️", name: "Hammer and Pick" },
		{ emoji: "🛠️", name: "Hammer and Wrench" },
		{ emoji: "⛏️", name: "Pick" },
		{ emoji: "🔩", name: "Nut and Bolt" },
		{ emoji: "⚙️", name: "Gear" },
		{ emoji: "🧱", name: "Brick" },
		{ emoji: "⛓️", name: "Chains" },
		{ emoji: "🧲", name: "Magnet" },
		{ emoji: "🔫", name: "Water Pistol" },
		{ emoji: "💣", name: "Bomb" },
		{ emoji: "🧨", name: "Firecracker" },
		{ emoji: "🔪", name: "Kitchen Knife" },
		{ emoji: "🗡️", name: "Dagger" },
		{ emoji: "⚔️", name: "Crossed Swords" },
		{ emoji: "🛡️", name: "Shield" },
		{ emoji: "🚬", name: "Cigarette" },
		{ emoji: "⚰️", name: "Coffin" },
		{ emoji: "⚱️", name: "Funeral Urn" },
		{ emoji: "🏺", name: "Amphora" },
		{ emoji: "🔮", name: "Crystal Ball" },
		{ emoji: "📿", name: "Prayer Beads" },
		{ emoji: "💈", name: "Barber Pole" },
		{ emoji: "⚗️", name: "Alembic" },
		{ emoji: "🔭", name: "Telescope" },
		{ emoji: "🔬", name: "Microscope" },
		{ emoji: "🕳️", name: "Hole" },
		{ emoji: "💊", name: "Pill" },
		{ emoji: "💉", name: "Syringe" },
		{ emoji: "🌡️", name: "Thermometer" },
		{ emoji: "🚽", name: "Toilet" },
		{ emoji: "🚰", name: "Potable Water" },
		{ emoji: "🚿", name: "Shower" },
		{ emoji: "🛁", name: "Bathtub" },
		{ emoji: "🛀", name: "Person Taking Bath" },
		{ emoji: "🧴", name: "Lotion Bottle" },
		{ emoji: "🧷", name: "Safety Pin" },
		{ emoji: "🧹", name: "Broom" },
		{ emoji: "🧺", name: "Basket" },
		{ emoji: "🧻", name: "Roll of Paper" },
		{ emoji: "🧼", name: "Soap" },
		{ emoji: "🧽", name: "Sponge" },
		{ emoji: "🧾", name: "Receipt" },
		{ emoji: "🛎️", name: "Bellhop Bell" },
		{ emoji: "🔑", name: "Key" },
		{ emoji: "🗝️", name: "Old Key" },
		{ emoji: "🚪", name: "Door" },
		{ emoji: "🛋️", name: "Couch and Lamp" },
		{ emoji: "🛏️", name: "Bed" },
		{ emoji: "🛌", name: "Person in Bed" },
		{ emoji: "🧸", name: "Teddy Bear" },
		{ emoji: "🖼️", name: "Framed Picture" },
		{ emoji: "🛍️", name: "Shopping Bags" },
		{ emoji: "🎁", name: "Wrapped Gift" },
		{ emoji: "🎀", name: "Ribbon" },
		{ emoji: "🎏", name: "Carp Streamer" },
		{ emoji: "🎐", name: "Wind Chime" },
		{ emoji: "🧧", name: "Red Envelope" },
		{ emoji: "✉️", name: "Envelope" },
		{ emoji: "📩", name: "Envelope with Arrow" },
		{ emoji: "📨", name: "Incoming Envelope" },
		{ emoji: "📧", name: "E-Mail" },
		{ emoji: "💌", name: "Love Letter" },
		{ emoji: "📥", name: "Inbox Tray" },
		{ emoji: "📤", name: "Outbox Tray" },
		{ emoji: "📦", name: "Package" },
		{ emoji: "🏷️", name: "Label" },
		{ emoji: "📪", name: "Closed Mailbox with Lowered Flag" },
		{ emoji: "📫", name: "Closed Mailbox with Raised Flag" },
		{ emoji: "📬", name: "Open Mailbox with Raised Flag" },
		{ emoji: "📭", name: "Open Mailbox with Lowered Flag" },
		{ emoji: "📮", name: "Postbox" },
		{ emoji: "📯", name: "Postal Horn" },
		{ emoji: "📜", name: "Scroll" },
		{ emoji: "📃", name: "Page with Curl" },
		{ emoji: "📄", name: "Page Facing Up" },
		{ emoji: "📑", name: "Bookmark Tabs" },
		{ emoji: "📊", name: "Bar Chart" },
		{ emoji: "📈", name: "Chart Increasing" },
		{ emoji: "📉", name: "Chart Decreasing" },
		{ emoji: "🗒️", name: "Spiral Notepad" },
		{ emoji: "🗓️", name: "Spiral Calendar" },
		{ emoji: "📆", name: "Tear-Off Calendar" },
		{ emoji: "📅", name: "Calendar" },
		{ emoji: "📇", name: "Card Index" },
		{ emoji: "🗃️", name: "Card File Box" },
		{ emoji: "🗳️", name: "Ballot Box with Ballot" },
		{ emoji: "🗄️", name: "File Cabinet" },
		{ emoji: "📋", name: "Clipboard" },
		{ emoji: "📁", name: "File Folder" },
		{ emoji: "📂", name: "Open File Folder" },
		{ emoji: "🗂️", name: "Card Index Dividers" },
		{ emoji: "🗞️", name: "Rolled-Up Newspaper" },
		{ emoji: "📰", name: "Newspaper" },
		{ emoji: "📓", name: "Notebook" },
		{ emoji: "📔", name: "Notebook with Decorative Cover" },
		{ emoji: "📒", name: "Ledger" },
		{ emoji: "📕", name: "Closed Book" },
		{ emoji: "📗", name: "Green Book" },
		{ emoji: "📘", name: "Blue Book" },
		{ emoji: "📙", name: "Orange Book" },
		{ emoji: "📚", name: "Books" },
		{ emoji: "📖", name: "Open Book" },
		{ emoji: "🔖", name: "Bookmark" },
		{ emoji: "🔗", name: "Link" },
		{ emoji: "📎", name: "Paperclip" },
		{ emoji: "🖇️", name: "Linked Paperclips" },
		{ emoji: "📐", name: "Triangular Ruler" },
		{ emoji: "📏", name: "Straight Ruler" },
		{ emoji: "📌", name: "Pushpin" },
		{ emoji: "📍", name: "Round Pushpin" },
		{ emoji: "✂️", name: "Scissors" },
		{ emoji: "🖊️", name: "Pen" },
		{ emoji: "🖋️", name: "Fountain Pen" },
		{ emoji: "✒️", name: "Black Nib" },
		{ emoji: "🖌️", name: "Paintbrush" },
		{ emoji: "🖍️", name: "Crayon" },
		{ emoji: "📝", name: "Memo" },
		{ emoji: "✏️", name: "Pencil" },
		{ emoji: "🔍", name: "Magnifying Glass Tilted Left" },
		{ emoji: "🔎", name: "Magnifying Glass Tilted Right" },
		{ emoji: "🔏", name: "Locked with Pen" },
		{ emoji: "🔐", name: "Locked with Key" },
		{ emoji: "🔒", name: "Locked" },
		{ emoji: "🔓", name: "Unlocked" },
	],

	// Symbols
	symbols: [
		{ emoji: "❤️", name: "Red Heart" },
		{ emoji: "🧡", name: "Orange Heart" },
		{ emoji: "💛", name: "Yellow Heart" },
		{ emoji: "💚", name: "Green Heart" },
		{ emoji: "💙", name: "Blue Heart" },
		{ emoji: "💜", name: "Purple Heart" },
		{ emoji: "🖤", name: "Black Heart" },
		{ emoji: "🤍", name: "White Heart" },
		{ emoji: "🤎", name: "Brown Heart" },
		{ emoji: "💔", name: "Broken Heart" },
		{ emoji: "❣️", name: "Heart Exclamation" },
		{ emoji: "💕", name: "Two Hearts" },
		{ emoji: "💞", name: "Revolving Hearts" },
		{ emoji: "💓", name: "Beating Heart" },
		{ emoji: "💗", name: "Growing Heart" },
		{ emoji: "💖", name: "Sparkling Heart" },
		{ emoji: "💘", name: "Heart with Arrow" },
		{ emoji: "💝", name: "Heart with Ribbon" },
		{ emoji: "💟", name: "Heart Decoration" },
		{ emoji: "☮️", name: "Peace Symbol" },
		{ emoji: "✝️", name: "Latin Cross" },
		{ emoji: "☪️", name: "Star and Crescent" },
		{ emoji: "🕉️", name: "Om" },
		{ emoji: "☸️", name: "Wheel of Dharma" },
		{ emoji: "✡️", name: "Star of David" },
		{ emoji: "🔯", name: "Dotted Six-Pointed Star" },
		{ emoji: "🕎", name: "Menorah" },
		{ emoji: "☯️", name: "Yin Yang" },
		{ emoji: "☦️", name: "Orthodox Cross" },
		{ emoji: "🛐", name: "Place of Worship" },
		{ emoji: "🆔", name: "ID Button" },
		{ emoji: "⚛️", name: "Atom Symbol" },
		{ emoji: "🉑", name: "Japanese Acceptable Button" },
		{ emoji: "☢️", name: "Radioactive" },
		{ emoji: "☣️", name: "Biohazard" },
		{ emoji: "📴", name: "Mobile Phone Off" },
		{ emoji: "📳", name: "Vibration Mode" },
		{ emoji: "🈶", name: "Japanese Not Free of Charge Button" },
		{ emoji: "🈚", name: "Japanese Free of Charge Button" },
		{ emoji: "🈸", name: "Japanese Application Button" },
		{ emoji: "🈺", name: "Japanese Open for Business Button" },
		{ emoji: "🈷️", name: "Japanese Monthly Amount Button" },
		{ emoji: "✴️", name: "Eight-Pointed Star" },
		{ emoji: "🆚", name: "VS Button" },
		{ emoji: "💮", name: "White Flower" },
		{ emoji: "🉐", name: "Japanese Bargain Button" },
		{ emoji: "㊙️", name: "Japanese Secret Button" },
		{ emoji: "㊗️", name: "Japanese Congratulations Button" },
		{ emoji: "🈴", name: "Japanese Passing Grade Button" },
		{ emoji: "🈵", name: "Japanese No Vacancy Button" },
		{ emoji: "🈹", name: "Japanese Discount Button" },
		{ emoji: "🈲", name: "Japanese Prohibited Button" },
		{ emoji: "🅰️", name: "A Button (Blood Type)" },
		{ emoji: "🅱️", name: "B Button (Blood Type)" },
		{ emoji: "🆎", name: "AB Button (Blood Type)" },
		{ emoji: "🆑", name: "CL Button" },
		{ emoji: "🅾️", name: "O Button (Blood Type)" },
		{ emoji: "🆘", name: "SOS Button" },
		{ emoji: "❌", name: "Cross Mark" },
		{ emoji: "⭕", name: "Hollow Red Circle" },
		{ emoji: "🛑", name: "Stop Sign" },
		{ emoji: "⛔", name: "No Entry" },
		{ emoji: "📛", name: "Name Badge" },
		{ emoji: "🚫", name: "Prohibited" },
		{ emoji: "💯", name: "Hundred Points" },
		{ emoji: "💢", name: "Anger Symbol" },
		{ emoji: "♨️", name: "Hot Springs" },
		{ emoji: "🚷", name: "No Pedestrians" },
		{ emoji: "🚯", name: "No Littering" },
		{ emoji: "🚳", name: "No Bicycles" },
		{ emoji: "🚱", name: "Non-Potable Water" },
		{ emoji: "🔞", name: "No One Under Eighteen" },
		{ emoji: "📵", name: "No Mobile Phones" },
		{ emoji: "🚭", name: "No Smoking" },
		{ emoji: "❗", name: "Exclamation Mark" },
		{ emoji: "❕", name: "White Exclamation Mark" },
		{ emoji: "❓", name: "Question Mark" },
		{ emoji: "❔", name: "White Question Mark" },
		{ emoji: "‼️", name: "Double Exclamation Mark" },
		{ emoji: "⁉️", name: "Exclamation Question Mark" },
		{ emoji: "🔅", name: "Dim Button" },
		{ emoji: "🔆", name: "Bright Button" },
		{ emoji: "〽️", name: "Part Alternation Mark" },
		{ emoji: "⚠️", name: "Warning" },
		{ emoji: "🚸", name: "Children Crossing" },
		{ emoji: "🔱", name: "Trident Emblem" },
		{ emoji: "⚜️", name: "Fleur-de-lis" },
		{ emoji: "🔰", name: "Japanese Symbol for Beginner" },
		{ emoji: "♻️", name: "Recycling Symbol" },
		{ emoji: "✅", name: "Check Mark Button" },
		{ emoji: "🈯", name: "Japanese Reserved Button" },
		{ emoji: "💹", name: "Chart Increasing with Yen" },
		{ emoji: "❇️", name: "Sparkle" },
		{ emoji: "✳️", name: "Eight-Spoked Asterisk" },
		{ emoji: "❎", name: "Cross Mark Button" },
		{ emoji: "🌐", name: "Globe with Meridians" },
		{ emoji: "💠", name: "Diamond with a Dot" },
		{ emoji: "Ⓜ️", name: "Circled M" },
		{ emoji: "🌀", name: "Cyclone" },
		{ emoji: "💤", name: "Zzz" },
		{ emoji: "🏧", name: "ATM Sign" },
		{ emoji: "🚾", name: "Water Closet" },
		{ emoji: "♿", name: "Wheelchair Symbol" },
		{ emoji: "🅿️", name: "P Button" },
		{ emoji: "🈳", name: "Japanese Vacancy Button" },
		{ emoji: "🈂️", name: "Japanese Service Charge Button" },
		{ emoji: "🛂", name: "Passport Control" },
		{ emoji: "🛃", name: "Customs" },
		{ emoji: "🛄", name: "Baggage Claim" },
		{ emoji: "🛅", name: "Left Luggage" },
		{ emoji: "🚹", name: "Mens Room" },
		{ emoji: "🚺", name: "Womens Room" },
		{ emoji: "🚼", name: "Baby Symbol" },
		{ emoji: "🚻", name: "Restroom" },
		{ emoji: "🚮", name: "Litter in Bin Sign" },
		{ emoji: "🎦", name: "Cinema" },
		{ emoji: "📶", name: "Antenna Bars" },
		{ emoji: "🈁", name: "Japanese Here Button" },
		{ emoji: "🔣", name: "Input Symbols" },
		{ emoji: "ℹ️", name: "Information" },
		{ emoji: "🔤", name: "Input Latin Letters" },
		{ emoji: "🔡", name: "Input Latin Lowercase" },
		{ emoji: "🔠", name: "Input Latin Uppercase" },
		{ emoji: "🆖", name: "NG Button" },
		{ emoji: "🆗", name: "OK Button" },
		{ emoji: "🆙", name: "UP! Button" },
		{ emoji: "🆒", name: "COOL Button" },
		{ emoji: "🆕", name: "NEW Button" },
		{ emoji: "🆓", name: "FREE Button" },
		{ emoji: "0️⃣", name: "Keycap Digit Zero" },
		{ emoji: "1️⃣", name: "Keycap Digit One" },
		{ emoji: "2️⃣", name: "Keycap Digit Two" },
		{ emoji: "3️⃣", name: "Keycap Digit Three" },
		{ emoji: "4️⃣", name: "Keycap Digit Four" },
		{ emoji: "5️⃣", name: "Keycap Digit Five" },
		{ emoji: "6️⃣", name: "Keycap Digit Six" },
		{ emoji: "7️⃣", name: "Keycap Digit Seven" },
		{ emoji: "8️⃣", name: "Keycap Digit Eight" },
		{ emoji: "9️⃣", name: "Keycap Digit Nine" },
		{ emoji: "🔟", name: "Keycap 10" },
		{ emoji: "🔢", name: "Input Numbers" },
		{ emoji: "#️⃣", name: "Keycap Number Sign" },
		{ emoji: "*️⃣", name: "Keycap Asterisk" },
		{ emoji: "⏏️", name: "Eject Button" },
		{ emoji: "▶️", name: "Play Button" },
		{ emoji: "⏸️", name: "Pause Button" },
		{ emoji: "⏯️", name: "Play or Pause Button" },
		{ emoji: "⏹️", name: "Stop Button" },
		{ emoji: "⏺️", name: "Record Button" },
		{ emoji: "⏭️", name: "Next Track Button" },
		{ emoji: "⏮️", name: "Last Track Button" },
		{ emoji: "⏩", name: "Fast-Forward Button" },
		{ emoji: "⏪", name: "Fast Reverse Button" },
		{ emoji: "⏫", name: "Fast Up Button" },
		{ emoji: "⏬", name: "Fast Down Button" },
		{ emoji: "◀️", name: "Reverse Button" },
		{ emoji: "🔼", name: "Upwards Button" },
		{ emoji: "🔽", name: "Downwards Button" },
		{ emoji: "➡️", name: "Right Arrow" },
		{ emoji: "⬅️", name: "Left Arrow" },
		{ emoji: "⬆️", name: "Up Arrow" },
		{ emoji: "⬇️", name: "Down Arrow" },
		{ emoji: "↗️", name: "Up-Right Arrow" },
		{ emoji: "↘️", name: "Down-Right Arrow" },
		{ emoji: "↙️", name: "Down-Left Arrow" },
		{ emoji: "↖️", name: "Up-Left Arrow" },
		{ emoji: "↕️", name: "Up-Down Arrow" },
		{ emoji: "↔️", name: "Left-Right Arrow" },
		{ emoji: "↪️", name: "Left Arrow Curving Right" },
		{ emoji: "↩️", name: "Right Arrow Curving Left" },
		{ emoji: "⤴️", name: "Right Arrow Curving Up" },
		{ emoji: "⤵️", name: "Right Arrow Curving Down" },
		{ emoji: "🔀", name: "Shuffle Tracks Button" },
		{ emoji: "🔁", name: "Repeat Button" },
		{ emoji: "🔂", name: "Repeat Single Button" },
		{ emoji: "🔄", name: "Counterclockwise Arrows Button" },
		{ emoji: "🔃", name: "Clockwise Vertical Arrows" },
		{ emoji: "🎵", name: "Musical Note" },
		{ emoji: "🎶", name: "Musical Notes" },
		{ emoji: "➕", name: "Plus Sign" },
		{ emoji: "➖", name: "Minus Sign" },
		{ emoji: "➗", name: "Division Sign" },
		{ emoji: "✖️", name: "Multiplication Sign" },
		{ emoji: "💲", name: "Heavy Dollar Sign" },
		{ emoji: "💱", name: "Currency Exchange" },
		{ emoji: "™️", name: "Trade Mark" },
		{ emoji: "©️", name: "Copyright" },
		{ emoji: "®️", name: "Registered" },
		{ emoji: "〰️", name: "Wavy Dash" },
		{ emoji: "➰", name: "Curly Loop" },
		{ emoji: "➿", name: "Double Curly Loop" },
		{ emoji: "🔚", name: "END Arrow" },
		{ emoji: "🔙", name: "BACK Arrow" },
		{ emoji: "🔛", name: "ON! Arrow" },
		{ emoji: "🔝", name: "TOP Arrow" },
		{ emoji: "🔜", name: "SOON Arrow" },
		{ emoji: "✔️", name: "Check Mark" },
		{ emoji: "☑️", name: "Check Box with Check" },
		{ emoji: "🔘", name: "Radio Button" },
		{ emoji: "⚪", name: "White Circle" },
		{ emoji: "⚫", name: "Black Circle" },
		{ emoji: "🔴", name: "Red Circle" },
		{ emoji: "🔵", name: "Blue Circle" },
		{ emoji: "🔺", name: "Red Triangle Pointed Up" },
		{ emoji: "🔻", name: "Red Triangle Pointed Down" },
		{ emoji: "🔸", name: "Small Orange Diamond" },
		{ emoji: "🔹", name: "Small Blue Diamond" },
		{ emoji: "🔶", name: "Large Orange Diamond" },
		{ emoji: "🔷", name: "Large Blue Diamond" },
		{ emoji: "🔳", name: "White Square Button" },
		{ emoji: "🔲", name: "Black Square Button" },
		{ emoji: "▪️", name: "Black Small Square" },
		{ emoji: "▫️", name: "White Small Square" },
		{ emoji: "◾", name: "Black Medium-Small Square" },
		{ emoji: "◽", name: "White Medium-Small Square" },
		{ emoji: "◼️", name: "Black Medium Square" },
		{ emoji: "◻️", name: "White Medium Square" },
		{ emoji: "⬛", name: "Black Large Square" },
		{ emoji: "⬜", name: "White Large Square" },
		{ emoji: "🟥", name: "Red Square" },
		{ emoji: "🟧", name: "Orange Square" },
		{ emoji: "🟨", name: "Yellow Square" },
		{ emoji: "🟩", name: "Green Square" },
		{ emoji: "🟦", name: "Blue Square" },
		{ emoji: "🟪", name: "Purple Square" },
		{ emoji: "🟫", name: "Brown Square" },
	],

	// Nature
	nature: [
		{ emoji: "💐", name: "Bouquet" },
		{ emoji: "🌸", name: "Cherry Blossom" },
		{ emoji: "💮", name: "White Flower" },
		{ emoji: "🏵️", name: "Rosette" },
		{ emoji: "🌹", name: "Rose" },
		{ emoji: "🥀", name: "Wilted Flower" },
		{ emoji: "🌺", name: "Hibiscus" },
		{ emoji: "🌻", name: "Sunflower" },
		{ emoji: "🌼", name: "Blossom" },
		{ emoji: "🌷", name: "Tulip" },
		{ emoji: "🌱", name: "Seedling" },
		{ emoji: "🌲", name: "Evergreen Tree" },
		{ emoji: "🌳", name: "Deciduous Tree" },
		{ emoji: "🌴", name: "Palm Tree" },
		{ emoji: "🌵", name: "Cactus" },
		{ emoji: "🌾", name: "Sheaf of Rice" },
		{ emoji: "🌿", name: "Herb" },
		{ emoji: "☘️", name: "Shamrock" },
		{ emoji: "🍀", name: "Four Leaf Clover" },
		{ emoji: "🍁", name: "Maple Leaf" },
		{ emoji: "🍂", name: "Fallen Leaf" },
		{ emoji: "🍃", name: "Leaf Fluttering in Wind" },
		{ emoji: "🌾", name: "Sheaf of Rice" },
	],

	// Weather
	weather: [
		{ emoji: "🌍", name: "Globe Showing Europe-Africa" },
		{ emoji: "🌎", name: "Globe Showing Americas" },
		{ emoji: "🌏", name: "Globe Showing Asia-Australia" },
		{ emoji: "🌐", name: "Globe with Meridians" },
		{ emoji: "🌑", name: "New Moon" },
		{ emoji: "🌒", name: "Waxing Crescent Moon" },
		{ emoji: "🌓", name: "First Quarter Moon" },
		{ emoji: "🌔", name: "Waxing Gibbous Moon" },
		{ emoji: "🌕", name: "Full Moon" },
		{ emoji: "🌖", name: "Waning Gibbous Moon" },
		{ emoji: "🌗", name: "Last Quarter Moon" },
		{ emoji: "🌘", name: "Waning Crescent Moon" },
		{ emoji: "🌙", name: "Crescent Moon" },
		{ emoji: "🌚", name: "New Moon Face" },
		{ emoji: "🌛", name: "First Quarter Moon Face" },
		{ emoji: "🌜", name: "Last Quarter Moon Face" },
		{ emoji: "🌡️", name: "Thermometer" },
		{ emoji: "☀️", name: "Sun" },
		{ emoji: "🌝", name: "Full Moon Face" },
		{ emoji: "🌞", name: "Sun with Face" },
		{ emoji: "⭐", name: "Star" },
		{ emoji: "🌟", name: "Glowing Star" },
		{ emoji: "🌠", name: "Shooting Star" },
		{ emoji: "☁️", name: "Cloud" },
		{ emoji: "⛅", name: "Sun Behind Cloud" },
		{ emoji: "⛈️", name: "Cloud with Lightning and Rain" },
		{ emoji: "🌤️", name: "Sun Behind Small Cloud" },
		{ emoji: "🌥️", name: "Sun Behind Large Cloud" },
		{ emoji: "🌦️", name: "Sun Behind Rain Cloud" },
		{ emoji: "🌧️", name: "Cloud with Rain" },
		{ emoji: "🌨️", name: "Cloud with Snow" },
		{ emoji: "🌩️", name: "Cloud with Lightning" },
		{ emoji: "🌪️", name: "Tornado" },
		{ emoji: "🌫️", name: "Fog" },
		{ emoji: "🌬️", name: "Wind Face" },
		{ emoji: "🌀", name: "Cyclone" },
		{ emoji: "🌈", name: "Rainbow" },
		{ emoji: "🌂", name: "Closed Umbrella" },
		{ emoji: "☂️", name: "Umbrella" },
		{ emoji: "☔", name: "Umbrella with Rain Drops" },
		{ emoji: "⛱️", name: "Umbrella on Ground" },
		{ emoji: "⚡", name: "High Voltage" },
		{ emoji: "❄️", name: "Snowflake" },
		{ emoji: "☃️", name: "Snowman" },
		{ emoji: "⛄", name: "Snowman Without Snow" },
		{ emoji: "☄️", name: "Comet" },
		{ emoji: "🔥", name: "Fire" },
		{ emoji: "💧", name: "Droplet" },
		{ emoji: "🌊", name: "Water Wave" },
	],

	// Celebration
	celebration: [
		{ emoji: "🎃", name: "Jack-O-Lantern" },
		{ emoji: "🎄", name: "Christmas Tree" },
		{ emoji: "🎆", name: "Fireworks" },
		{ emoji: "🎇", name: "Sparkler" },
		{ emoji: "🧨", name: "Firecracker" },
		{ emoji: "✨", name: "Sparkles" },
		{ emoji: "🎈", name: "Balloon" },
		{ emoji: "🎉", name: "Party Popper" },
		{ emoji: "🎊", name: "Confetti Ball" },
		{ emoji: "🎋", name: "Tanabata Tree" },
		{ emoji: "🎍", name: "Pine Decoration" },
		{ emoji: "🎎", name: "Japanese Dolls" },
		{ emoji: "🎑", name: "Moon Viewing Ceremony" },
		{ emoji: "🎀", name: "Ribbon" },
		{ emoji: "🎁", name: "Wrapped Gift" },
		{ emoji: "🎗️", name: "Reminder Ribbon" },
		{ emoji: "🎟️", name: "Admission Tickets" },
		{ emoji: "🎫", name: "Ticket" },
		{ emoji: "🎖️", name: "Military Medal" },
		{ emoji: "🏅", name: "Sports Medal" },
		{ emoji: "🥇", name: "1st Place Medal" },
		{ emoji: "🥈", name: "2nd Place Medal" },
		{ emoji: "🥉", name: "3rd Place Medal" },
	],

	// Clothing
	clothing: [
		{ emoji: "👓", name: "Glasses" },
		{ emoji: "🕶️", name: "Sunglasses" },
		{ emoji: "🥽", name: "Goggles" },
		{ emoji: "🥼", name: "Lab Coat" },
		{ emoji: "🦺", name: "Safety Vest" },
		{ emoji: "👔", name: "Necktie" },
		{ emoji: "👕", name: "T-Shirt" },
		{ emoji: "👖", name: "Jeans" },
		{ emoji: "🧣", name: "Scarf" },
		{ emoji: "🧤", name: "Gloves" },
		{ emoji: "🧥", name: "Coat" },
		{ emoji: "🧦", name: "Socks" },
		{ emoji: "👗", name: "Dress" },
		{ emoji: "👘", name: "Kimono" },
		{ emoji: "🥻", name: "Sari" },
		{ emoji: "🩱", name: "One-Piece Swimsuit" },
		{ emoji: "🩲", name: "Briefs" },
		{ emoji: "🩳", name: "Shorts" },
		{ emoji: "👙", name: "Bikini" },
		{ emoji: "👚", name: "Womans Clothes" },
		{ emoji: "👛", name: "Purse" },
		{ emoji: "👜", name: "Handbag" },
		{ emoji: "👝", name: "Clutch Bag" },
		{ emoji: "🎒", name: "Backpack" },
		{ emoji: "👞", name: "Mans Shoe" },
		{ emoji: "👟", name: "Running Shoe" },
		{ emoji: "🥾", name: "Hiking Boot" },
		{ emoji: "🥿", name: "Flat Shoe" },
		{ emoji: "👠", name: "High-Heeled Shoe" },
		{ emoji: "👡", name: "Womans Sandal" },
		{ emoji: "🩰", name: "Ballet Shoes" },
		{ emoji: "👢", name: "Womans Boot" },
		{ emoji: "👑", name: "Crown" },
		{ emoji: "👒", name: "Womans Hat" },
		{ emoji: "🎩", name: "Top Hat" },
		{ emoji: "🎓", name: "Graduation Cap" },
		{ emoji: "🧢", name: "Billed Cap" },
		{ emoji: "⛑️", name: "Rescue Workers Helmet" },
		{ emoji: "📿", name: "Prayer Beads" },
		{ emoji: "💄", name: "Lipstick" },
		{ emoji: "💍", name: "Ring" },
		{ emoji: "💎", name: "Gem Stone" },
	],

	// Additional Miscellaneous
	misc: [
		{ emoji: "🌂", name: "Closed Umbrella" },
		{ emoji: "☂️", name: "Umbrella" },
		{ emoji: "☔", name: "Umbrella with Rain Drops" },
		{ emoji: "💫", name: "Dizzy" },
		{ emoji: "💥", name: "Collision" },
		{ emoji: "💦", name: "Sweat Droplets" },
		{ emoji: "💨", name: "Dashing Away" },
		{ emoji: "🕳️", name: "Hole" },
		{ emoji: "💣", name: "Bomb" },
		{ emoji: "💬", name: "Speech Balloon" },
		{ emoji: "👁️‍🗨️", name: "Eye in Speech Bubble" },
		{ emoji: "🗨️", name: "Left Speech Bubble" },
		{ emoji: "🗯️", name: "Right Anger Bubble" },
		{ emoji: "💭", name: "Thought Balloon" },
		{ emoji: "💤", name: "Zzz" },
		{ emoji: "🎴", name: "Flower Playing Cards" },
		{ emoji: "🀄", name: "Mahjong Red Dragon" },
		{ emoji: "🃏", name: "Joker" },
		{ emoji: "🎴", name: "Flower Playing Cards" },
		{ emoji: "🔇", name: "Muted Speaker" },
		{ emoji: "🔈", name: "Speaker Low Volume" },
		{ emoji: "🔉", name: "Speaker Medium Volume" },
		{ emoji: "🔊", name: "Speaker High Volume" },
		{ emoji: "📢", name: "Loudspeaker" },
		{ emoji: "📣", name: "Megaphone" },
		{ emoji: "📯", name: "Postal Horn" },
		{ emoji: "🔔", name: "Bell" },
		{ emoji: "🔕", name: "Bell with Slash" },
		{ emoji: "🎼", name: "Musical Score" },
		{ emoji: "🎵", name: "Musical Note" },
		{ emoji: "🎶", name: "Musical Notes" },
		{ emoji: "🎙️", name: "Studio Microphone" },
		{ emoji: "🎚️", name: "Level Slider" },
		{ emoji: "🎛️", name: "Control Knobs" },
		{ emoji: "📻", name: "Radio" },
		{ emoji: "🧬", name: "DNA" },
		{ emoji: "🔬", name: "Microscope" },
		{ emoji: "🔭", name: "Telescope" },
		{ emoji: "📡", name: "Satellite Antenna" },
		{ emoji: "💉", name: "Syringe" },
		{ emoji: "🩸", name: "Drop of Blood" },
		{ emoji: "💊", name: "Pill" },
		{ emoji: "🩹", name: "Adhesive Bandage" },
		{ emoji: "🩺", name: "Stethoscope" },
		{ emoji: "🚪", name: "Door" },
		{ emoji: "🪟", name: "Window" },
		{ emoji: "🛏️", name: "Bed" },
		{ emoji: "🛋️", name: "Couch and Lamp" },
		{ emoji: "🪑", name: "Chair" },
		{ emoji: "🚽", name: "Toilet" },
		{ emoji: "🚿", name: "Shower" },
		{ emoji: "🛁", name: "Bathtub" },
		{ emoji: "🪒", name: "Razor" },
		{ emoji: "🧴", name: "Lotion Bottle" },
		{ emoji: "🧷", name: "Safety Pin" },
		{ emoji: "🧹", name: "Broom" },
		{ emoji: "🧺", name: "Basket" },
		{ emoji: "🧻", name: "Roll of Paper" },
		{ emoji: "🧼", name: "Soap" },
		{ emoji: "🧽", name: "Sponge" },
		{ emoji: "🧯", name: "Fire Extinguisher" },
		{ emoji: "🛒", name: "Shopping Cart" },
		{ emoji: "🚬", name: "Cigarette" },
		{ emoji: "⚰️", name: "Coffin" },
		{ emoji: "⚱️", name: "Funeral Urn" },
		{ emoji: "🗿", name: "Moai" },
		{ emoji: "🪧", name: "Placard" },
	],

	// Body Parts
	bodyParts: [
		{ emoji: "👋", name: "Waving Hand" },
		{ emoji: "🤚", name: "Raised Back of Hand" },
		{ emoji: "🖐️", name: "Hand with Fingers Splayed" },
		{ emoji: "✋", name: "Raised Hand" },
		{ emoji: "🖖", name: "Vulcan Salute" },
		{ emoji: "👌", name: "OK Hand" },
		{ emoji: "🤏", name: "Pinching Hand" },
		{ emoji: "✌️", name: "Victory Hand" },
		{ emoji: "🤞", name: "Crossed Fingers" },
		{ emoji: "🤟", name: "Love-You Gesture" },
		{ emoji: "🤘", name: "Sign of the Horns" },
		{ emoji: "🤙", name: "Call Me Hand" },
		{ emoji: "👈", name: "Backhand Index Pointing Left" },
		{ emoji: "👉", name: "Backhand Index Pointing Right" },
		{ emoji: "👆", name: "Backhand Index Pointing Up" },
		{ emoji: "🖕", name: "Middle Finger" },
		{ emoji: "👇", name: "Backhand Index Pointing Down" },
		{ emoji: "☝️", name: "Index Pointing Up" },
		{ emoji: "👍", name: "Thumbs Up" },
		{ emoji: "👎", name: "Thumbs Down" },
		{ emoji: "✊", name: "Raised Fist" },
		{ emoji: "👊", name: "Oncoming Fist" },
		{ emoji: "🤛", name: "Left-Facing Fist" },
		{ emoji: "🤜", name: "Right-Facing Fist" },
		{ emoji: "👏", name: "Clapping Hands" },
		{ emoji: "🙌", name: "Raising Hands" },
		{ emoji: "👐", name: "Open Hands" },
		{ emoji: "🤲", name: "Palms Up Together" },
		{ emoji: "🤝", name: "Handshake" },
		{ emoji: "🙏", name: "Folded Hands" },
		{ emoji: "✍️", name: "Writing Hand" },
		{ emoji: "💅", name: "Nail Polish" },
		{ emoji: "🤳", name: "Selfie" },
		{ emoji: "💪", name: "Flexed Biceps" },
		{ emoji: "🦾", name: "Mechanical Arm" },
		{ emoji: "🦿", name: "Mechanical Leg" },
		{ emoji: "🦵", name: "Leg" },
		{ emoji: "🦶", name: "Foot" },
		{ emoji: "👂", name: "Ear" },
		{ emoji: "🦻", name: "Ear with Hearing Aid" },
		{ emoji: "👃", name: "Nose" },
		{ emoji: "🧠", name: "Brain" },
		{ emoji: "🦷", name: "Tooth" },
		{ emoji: "🦴", name: "Bone" },
		{ emoji: "👀", name: "Eyes" },
		{ emoji: "👁️", name: "Eye" },
		{ emoji: "👅", name: "Tongue" },
		{ emoji: "👄", name: "Mouth" },
	],

	// Additional Fun Emojis
	extraFun: [
		{ emoji: "🪀", name: "Yo-Yo" },
		{ emoji: "🪁", name: "Kite" },
		{ emoji: "🥌", name: "Curling Stone" },
		{ emoji: "🪃", name: "Boomerang" },
		{ emoji: "🪂", name: "Parachute" },
		{ emoji: "🧿", name: "Nazar Amulet" },
		{ emoji: "🧵", name: "Thread" },
		{ emoji: "🧶", name: "Yarn" },
	],
};

function generateCalendar() {
	// Flatten all categories into a single array
	const allEmojis = [];
	for (const category of Object.values(emojiCategories)) {
		allEmojis.push(...category);
	}

	// Remove duplicates based on emoji character
	const uniqueEmojisMap = new Map();
	for (const item of allEmojis) {
		if (!uniqueEmojisMap.has(item.emoji)) {
			uniqueEmojisMap.set(item.emoji, item);
		}
	}

	const uniqueEmojis = Array.from(uniqueEmojisMap.values());

	console.log(`Generated ${uniqueEmojis.length} unique emojis`);
	console.log(
		`Target: 1096 emojis (3 years = 365 + 365 + 366 including 1 leap year)`,
	);

	// Check if we have enough emojis
	if (uniqueEmojis.length < 1096) {
		console.error(
			`❌ Not enough emojis! Need 1096, have ${uniqueEmojis.length}`,
		);
		process.exit(1);
	}

	// Simple shuffle for good distribution
	const shuffled = uniqueEmojis.sort(() => Math.random() - 0.5);

	// Take first 1096
	const result = shuffled.slice(0, 1096);

	return result;
}

// Generate and save the calendar
const calendar = generateCalendar();
const outputPath = join(__dirname, "../data/emoji_calendar.json");
writeFileSync(outputPath, JSON.stringify(calendar, null, 2));

console.log(
	`\n✅ Emoji calendar saved to ${outputPath}\nTotal unique emojis: ${calendar.length}`,
);
